// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class EndpointsConnectorAgentEnrollmentToken extends pulumi.CustomResource {
    /**
     * Get an existing EndpointsConnectorAgentEnrollmentToken resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: EndpointsConnectorAgentEnrollmentTokenState, opts?: pulumi.CustomResourceOptions): EndpointsConnectorAgentEnrollmentToken {
        return new EndpointsConnectorAgentEnrollmentToken(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'authentik:index/endpointsConnectorAgentEnrollmentToken:EndpointsConnectorAgentEnrollmentToken';

    /**
     * Returns true if the given object is an instance of EndpointsConnectorAgentEnrollmentToken.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is EndpointsConnectorAgentEnrollmentToken {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === EndpointsConnectorAgentEnrollmentToken.__pulumiType;
    }

    declare public readonly connector: pulumi.Output<string>;
    declare public readonly deviceAccessGroup: pulumi.Output<string | undefined>;
    declare public readonly endpointsConnectorAgentEnrollmentTokenId: pulumi.Output<string>;
    declare public readonly expires: pulumi.Output<string | undefined>;
    /**
     * Generated.
     */
    declare public /*out*/ readonly expiresIn: pulumi.Output<number>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
     */
    declare public readonly expiring: pulumi.Output<boolean | undefined>;
    /**
     * Generated.
     */
    declare public /*out*/ readonly key: pulumi.Output<string>;
    declare public readonly name: pulumi.Output<string>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
     */
    declare public readonly retrieveKey: pulumi.Output<boolean | undefined>;

    /**
     * Create a EndpointsConnectorAgentEnrollmentToken resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: EndpointsConnectorAgentEnrollmentTokenArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: EndpointsConnectorAgentEnrollmentTokenArgs | EndpointsConnectorAgentEnrollmentTokenState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as EndpointsConnectorAgentEnrollmentTokenState | undefined;
            resourceInputs["connector"] = state?.connector;
            resourceInputs["deviceAccessGroup"] = state?.deviceAccessGroup;
            resourceInputs["endpointsConnectorAgentEnrollmentTokenId"] = state?.endpointsConnectorAgentEnrollmentTokenId;
            resourceInputs["expires"] = state?.expires;
            resourceInputs["expiresIn"] = state?.expiresIn;
            resourceInputs["expiring"] = state?.expiring;
            resourceInputs["key"] = state?.key;
            resourceInputs["name"] = state?.name;
            resourceInputs["retrieveKey"] = state?.retrieveKey;
        } else {
            const args = argsOrState as EndpointsConnectorAgentEnrollmentTokenArgs | undefined;
            if (args?.connector === undefined && !opts.urn) {
                throw new Error("Missing required property 'connector'");
            }
            resourceInputs["connector"] = args?.connector;
            resourceInputs["deviceAccessGroup"] = args?.deviceAccessGroup;
            resourceInputs["endpointsConnectorAgentEnrollmentTokenId"] = args?.endpointsConnectorAgentEnrollmentTokenId;
            resourceInputs["expires"] = args?.expires;
            resourceInputs["expiring"] = args?.expiring;
            resourceInputs["name"] = args?.name;
            resourceInputs["retrieveKey"] = args?.retrieveKey;
            resourceInputs["expiresIn"] = undefined /*out*/;
            resourceInputs["key"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["key"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(EndpointsConnectorAgentEnrollmentToken.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering EndpointsConnectorAgentEnrollmentToken resources.
 */
export interface EndpointsConnectorAgentEnrollmentTokenState {
    connector?: pulumi.Input<string | undefined>;
    deviceAccessGroup?: pulumi.Input<string | undefined>;
    endpointsConnectorAgentEnrollmentTokenId?: pulumi.Input<string | undefined>;
    expires?: pulumi.Input<string | undefined>;
    /**
     * Generated.
     */
    expiresIn?: pulumi.Input<number | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
     */
    expiring?: pulumi.Input<boolean | undefined>;
    /**
     * Generated.
     */
    key?: pulumi.Input<string | undefined>;
    name?: pulumi.Input<string | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
     */
    retrieveKey?: pulumi.Input<boolean | undefined>;
}

/**
 * The set of arguments for constructing a EndpointsConnectorAgentEnrollmentToken resource.
 */
export interface EndpointsConnectorAgentEnrollmentTokenArgs {
    connector: pulumi.Input<string>;
    deviceAccessGroup?: pulumi.Input<string | undefined>;
    endpointsConnectorAgentEnrollmentTokenId?: pulumi.Input<string | undefined>;
    expires?: pulumi.Input<string | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
     */
    expiring?: pulumi.Input<boolean | undefined>;
    name?: pulumi.Input<string | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
     */
    retrieveKey?: pulumi.Input<boolean | undefined>;
}
