// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class EndpointsConnectorAgent extends pulumi.CustomResource {
    /**
     * Get an existing EndpointsConnectorAgent resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: EndpointsConnectorAgentState, opts?: pulumi.CustomResourceOptions): EndpointsConnectorAgent {
        return new EndpointsConnectorAgent(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'authentik:index/endpointsConnectorAgent:EndpointsConnectorAgent';

    /**
     * Returns true if the given object is an instance of EndpointsConnectorAgent.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is EndpointsConnectorAgent {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === EndpointsConnectorAgent.__pulumiType;
    }

    /**
     * Format: hours=1;minutes=2;seconds=3. Defaults to `hours=8`.
     */
    declare public readonly authSessionDuration: pulumi.Output<string | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
     */
    declare public readonly authTerminateSessionOnExpiry: pulumi.Output<boolean | undefined>;
    declare public readonly authorizationFlow: pulumi.Output<string | undefined>;
    /**
     * Format: hours=1;minutes=2;seconds=3. Defaults to `seconds=3`.
     */
    declare public readonly challengeIdleTimeout: pulumi.Output<string | undefined>;
    declare public readonly challengeKey: pulumi.Output<string | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
     */
    declare public readonly challengeTriggerCheckIn: pulumi.Output<boolean | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
     */
    declare public readonly enabled: pulumi.Output<boolean | undefined>;
    declare public readonly endpointsConnectorAgentId: pulumi.Output<string>;
    declare public readonly jwtFederationProviders: pulumi.Output<number[] | undefined>;
    declare public readonly name: pulumi.Output<string>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`4000`" pulumi-lang-dotnet="`4000`" pulumi-lang-go="`4000`" pulumi-lang-python="`4000`" pulumi-lang-yaml="`4000`" pulumi-lang-java="`4000`" pulumi-lang-hcl="`4000`">`4000`</span>.
     */
    declare public readonly nssGidOffset: pulumi.Output<number | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`2000`" pulumi-lang-dotnet="`2000`" pulumi-lang-go="`2000`" pulumi-lang-python="`2000`" pulumi-lang-yaml="`2000`" pulumi-lang-java="`2000`" pulumi-lang-hcl="`2000`">`2000`</span>.
     */
    declare public readonly nssUidOffset: pulumi.Output<number | undefined>;
    /**
     * Format: hours=1;minutes=2;seconds=3. Defaults to `minutes=30`.
     */
    declare public readonly refreshInterval: pulumi.Output<string | undefined>;
    /**
     * Format: hours=1;minutes=2;seconds=3. Defaults to `hours=24`.
     */
    declare public readonly snapshotExpiry: pulumi.Output<string | undefined>;

    /**
     * Create a EndpointsConnectorAgent resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: EndpointsConnectorAgentArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: EndpointsConnectorAgentArgs | EndpointsConnectorAgentState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as EndpointsConnectorAgentState | undefined;
            resourceInputs["authSessionDuration"] = state?.authSessionDuration;
            resourceInputs["authTerminateSessionOnExpiry"] = state?.authTerminateSessionOnExpiry;
            resourceInputs["authorizationFlow"] = state?.authorizationFlow;
            resourceInputs["challengeIdleTimeout"] = state?.challengeIdleTimeout;
            resourceInputs["challengeKey"] = state?.challengeKey;
            resourceInputs["challengeTriggerCheckIn"] = state?.challengeTriggerCheckIn;
            resourceInputs["enabled"] = state?.enabled;
            resourceInputs["endpointsConnectorAgentId"] = state?.endpointsConnectorAgentId;
            resourceInputs["jwtFederationProviders"] = state?.jwtFederationProviders;
            resourceInputs["name"] = state?.name;
            resourceInputs["nssGidOffset"] = state?.nssGidOffset;
            resourceInputs["nssUidOffset"] = state?.nssUidOffset;
            resourceInputs["refreshInterval"] = state?.refreshInterval;
            resourceInputs["snapshotExpiry"] = state?.snapshotExpiry;
        } else {
            const args = argsOrState as EndpointsConnectorAgentArgs | undefined;
            resourceInputs["authSessionDuration"] = args?.authSessionDuration;
            resourceInputs["authTerminateSessionOnExpiry"] = args?.authTerminateSessionOnExpiry;
            resourceInputs["authorizationFlow"] = args?.authorizationFlow;
            resourceInputs["challengeIdleTimeout"] = args?.challengeIdleTimeout;
            resourceInputs["challengeKey"] = args?.challengeKey;
            resourceInputs["challengeTriggerCheckIn"] = args?.challengeTriggerCheckIn;
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["endpointsConnectorAgentId"] = args?.endpointsConnectorAgentId;
            resourceInputs["jwtFederationProviders"] = args?.jwtFederationProviders;
            resourceInputs["name"] = args?.name;
            resourceInputs["nssGidOffset"] = args?.nssGidOffset;
            resourceInputs["nssUidOffset"] = args?.nssUidOffset;
            resourceInputs["refreshInterval"] = args?.refreshInterval;
            resourceInputs["snapshotExpiry"] = args?.snapshotExpiry;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(EndpointsConnectorAgent.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering EndpointsConnectorAgent resources.
 */
export interface EndpointsConnectorAgentState {
    /**
     * Format: hours=1;minutes=2;seconds=3. Defaults to `hours=8`.
     */
    authSessionDuration?: pulumi.Input<string | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
     */
    authTerminateSessionOnExpiry?: pulumi.Input<boolean | undefined>;
    authorizationFlow?: pulumi.Input<string | undefined>;
    /**
     * Format: hours=1;minutes=2;seconds=3. Defaults to `seconds=3`.
     */
    challengeIdleTimeout?: pulumi.Input<string | undefined>;
    challengeKey?: pulumi.Input<string | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
     */
    challengeTriggerCheckIn?: pulumi.Input<boolean | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
     */
    enabled?: pulumi.Input<boolean | undefined>;
    endpointsConnectorAgentId?: pulumi.Input<string | undefined>;
    jwtFederationProviders?: pulumi.Input<pulumi.Input<number>[] | undefined>;
    name?: pulumi.Input<string | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`4000`" pulumi-lang-dotnet="`4000`" pulumi-lang-go="`4000`" pulumi-lang-python="`4000`" pulumi-lang-yaml="`4000`" pulumi-lang-java="`4000`" pulumi-lang-hcl="`4000`">`4000`</span>.
     */
    nssGidOffset?: pulumi.Input<number | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`2000`" pulumi-lang-dotnet="`2000`" pulumi-lang-go="`2000`" pulumi-lang-python="`2000`" pulumi-lang-yaml="`2000`" pulumi-lang-java="`2000`" pulumi-lang-hcl="`2000`">`2000`</span>.
     */
    nssUidOffset?: pulumi.Input<number | undefined>;
    /**
     * Format: hours=1;minutes=2;seconds=3. Defaults to `minutes=30`.
     */
    refreshInterval?: pulumi.Input<string | undefined>;
    /**
     * Format: hours=1;minutes=2;seconds=3. Defaults to `hours=24`.
     */
    snapshotExpiry?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a EndpointsConnectorAgent resource.
 */
export interface EndpointsConnectorAgentArgs {
    /**
     * Format: hours=1;minutes=2;seconds=3. Defaults to `hours=8`.
     */
    authSessionDuration?: pulumi.Input<string | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
     */
    authTerminateSessionOnExpiry?: pulumi.Input<boolean | undefined>;
    authorizationFlow?: pulumi.Input<string | undefined>;
    /**
     * Format: hours=1;minutes=2;seconds=3. Defaults to `seconds=3`.
     */
    challengeIdleTimeout?: pulumi.Input<string | undefined>;
    challengeKey?: pulumi.Input<string | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
     */
    challengeTriggerCheckIn?: pulumi.Input<boolean | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
     */
    enabled?: pulumi.Input<boolean | undefined>;
    endpointsConnectorAgentId?: pulumi.Input<string | undefined>;
    jwtFederationProviders?: pulumi.Input<pulumi.Input<number>[] | undefined>;
    name?: pulumi.Input<string | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`4000`" pulumi-lang-dotnet="`4000`" pulumi-lang-go="`4000`" pulumi-lang-python="`4000`" pulumi-lang-yaml="`4000`" pulumi-lang-java="`4000`" pulumi-lang-hcl="`4000`">`4000`</span>.
     */
    nssGidOffset?: pulumi.Input<number | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`2000`" pulumi-lang-dotnet="`2000`" pulumi-lang-go="`2000`" pulumi-lang-python="`2000`" pulumi-lang-yaml="`2000`" pulumi-lang-java="`2000`" pulumi-lang-hcl="`2000`">`2000`</span>.
     */
    nssUidOffset?: pulumi.Input<number | undefined>;
    /**
     * Format: hours=1;minutes=2;seconds=3. Defaults to `minutes=30`.
     */
    refreshInterval?: pulumi.Input<string | undefined>;
    /**
     * Format: hours=1;minutes=2;seconds=3. Defaults to `hours=24`.
     */
    snapshotExpiry?: pulumi.Input<string | undefined>;
}
