// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class EndpointsGoogleChromeConnector extends pulumi.CustomResource {
    /**
     * Get an existing EndpointsGoogleChromeConnector resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: EndpointsGoogleChromeConnectorState, opts?: pulumi.CustomResourceOptions): EndpointsGoogleChromeConnector {
        return new EndpointsGoogleChromeConnector(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'authentik:index/endpointsGoogleChromeConnector:EndpointsGoogleChromeConnector';

    /**
     * Returns true if the given object is an instance of EndpointsGoogleChromeConnector.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is EndpointsGoogleChromeConnector {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === EndpointsGoogleChromeConnector.__pulumiType;
    }

    /**
     * Generated.
     */
    declare public /*out*/ readonly chromeUrl: pulumi.Output<string>;
    /**
     * JSON format expected. Use `jsonencode()` to pass objects.
     */
    declare public readonly credentials: pulumi.Output<string>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
     */
    declare public readonly enabled: pulumi.Output<boolean | undefined>;
    declare public readonly endpointsGoogleChromeConnectorId: pulumi.Output<string>;
    declare public readonly name: pulumi.Output<string>;

    /**
     * Create a EndpointsGoogleChromeConnector resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: EndpointsGoogleChromeConnectorArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: EndpointsGoogleChromeConnectorArgs | EndpointsGoogleChromeConnectorState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as EndpointsGoogleChromeConnectorState | undefined;
            resourceInputs["chromeUrl"] = state?.chromeUrl;
            resourceInputs["credentials"] = state?.credentials;
            resourceInputs["enabled"] = state?.enabled;
            resourceInputs["endpointsGoogleChromeConnectorId"] = state?.endpointsGoogleChromeConnectorId;
            resourceInputs["name"] = state?.name;
        } else {
            const args = argsOrState as EndpointsGoogleChromeConnectorArgs | undefined;
            if (args?.credentials === undefined && !opts.urn) {
                throw new Error("Missing required property 'credentials'");
            }
            resourceInputs["credentials"] = args?.credentials;
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["endpointsGoogleChromeConnectorId"] = args?.endpointsGoogleChromeConnectorId;
            resourceInputs["name"] = args?.name;
            resourceInputs["chromeUrl"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(EndpointsGoogleChromeConnector.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering EndpointsGoogleChromeConnector resources.
 */
export interface EndpointsGoogleChromeConnectorState {
    /**
     * Generated.
     */
    chromeUrl?: pulumi.Input<string | undefined>;
    /**
     * JSON format expected. Use `jsonencode()` to pass objects.
     */
    credentials?: pulumi.Input<string | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
     */
    enabled?: pulumi.Input<boolean | undefined>;
    endpointsGoogleChromeConnectorId?: pulumi.Input<string | undefined>;
    name?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a EndpointsGoogleChromeConnector resource.
 */
export interface EndpointsGoogleChromeConnectorArgs {
    /**
     * JSON format expected. Use `jsonencode()` to pass objects.
     */
    credentials: pulumi.Input<string>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
     */
    enabled?: pulumi.Input<boolean | undefined>;
    endpointsGoogleChromeConnectorId?: pulumi.Input<string | undefined>;
    name?: pulumi.Input<string | undefined>;
}
