// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class EndpointsDeviceAccessGroup extends pulumi.CustomResource {
    /**
     * Get an existing EndpointsDeviceAccessGroup resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: EndpointsDeviceAccessGroupState, opts?: pulumi.CustomResourceOptions): EndpointsDeviceAccessGroup {
        return new EndpointsDeviceAccessGroup(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'authentik:index/endpointsDeviceAccessGroup:EndpointsDeviceAccessGroup';

    /**
     * Returns true if the given object is an instance of EndpointsDeviceAccessGroup.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is EndpointsDeviceAccessGroup {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === EndpointsDeviceAccessGroup.__pulumiType;
    }

    declare public readonly endpointsDeviceAccessGroupId: pulumi.Output<string>;
    declare public readonly name: pulumi.Output<string>;

    /**
     * Create a EndpointsDeviceAccessGroup resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: EndpointsDeviceAccessGroupArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: EndpointsDeviceAccessGroupArgs | EndpointsDeviceAccessGroupState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as EndpointsDeviceAccessGroupState | undefined;
            resourceInputs["endpointsDeviceAccessGroupId"] = state?.endpointsDeviceAccessGroupId;
            resourceInputs["name"] = state?.name;
        } else {
            const args = argsOrState as EndpointsDeviceAccessGroupArgs | undefined;
            resourceInputs["endpointsDeviceAccessGroupId"] = args?.endpointsDeviceAccessGroupId;
            resourceInputs["name"] = args?.name;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(EndpointsDeviceAccessGroup.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering EndpointsDeviceAccessGroup resources.
 */
export interface EndpointsDeviceAccessGroupState {
    endpointsDeviceAccessGroupId?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a EndpointsDeviceAccessGroup resource.
 */
export interface EndpointsDeviceAccessGroupArgs {
    endpointsDeviceAccessGroupId?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
}
