// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getApplicationEntitlement(args?: GetApplicationEntitlementArgs, opts?: pulumi.InvokeOptions): Promise<GetApplicationEntitlementResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("authentik:index/getApplicationEntitlement:getApplicationEntitlement", {
        "app": args.app,
        "id": args.id,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getApplicationEntitlement.
 */
export interface GetApplicationEntitlementArgs {
    app?: string;
    id?: string;
    name?: string;
}

/**
 * A collection of values returned by getApplicationEntitlement.
 */
export interface GetApplicationEntitlementResult {
    readonly app: string;
    readonly attributes: string;
    readonly id: string;
    readonly name: string;
}
export function getApplicationEntitlementOutput(args?: GetApplicationEntitlementOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetApplicationEntitlementResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("authentik:index/getApplicationEntitlement:getApplicationEntitlement", {
        "app": args.app,
        "id": args.id,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getApplicationEntitlement.
 */
export interface GetApplicationEntitlementOutputArgs {
    app?: pulumi.Input<string | undefined>;
    id?: pulumi.Input<string | undefined>;
    name?: pulumi.Input<string | undefined>;
}
