// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getPolicyExpression(args?: GetPolicyExpressionArgs, opts?: pulumi.InvokeOptions): Promise<GetPolicyExpressionResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("authentik:index/getPolicyExpression:getPolicyExpression", {
        "id": args.id,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getPolicyExpression.
 */
export interface GetPolicyExpressionArgs {
    id?: string;
    name?: string;
}

/**
 * A collection of values returned by getPolicyExpression.
 */
export interface GetPolicyExpressionResult {
    readonly boundTo: number;
    readonly component: string;
    readonly executionLogging: boolean;
    readonly expression: string;
    readonly id: string;
    readonly metaModelName: string;
    readonly name: string;
    readonly verboseName: string;
    readonly verboseNamePlural: string;
}
export function getPolicyExpressionOutput(args?: GetPolicyExpressionOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetPolicyExpressionResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("authentik:index/getPolicyExpression:getPolicyExpression", {
        "id": args.id,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getPolicyExpression.
 */
export interface GetPolicyExpressionOutputArgs {
    id?: pulumi.Input<string | undefined>;
    name?: pulumi.Input<string | undefined>;
}
