// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getPolicyBinding(args?: GetPolicyBindingArgs, opts?: pulumi.InvokeOptions): Promise<GetPolicyBindingResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("authentik:index/getPolicyBinding:getPolicyBinding", {
        "group": args.group,
        "id": args.id,
        "order": args.order,
        "policy": args.policy,
        "target": args.target,
        "user": args.user,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getPolicyBinding.
 */
export interface GetPolicyBindingArgs {
    group?: string;
    id?: string;
    order?: number;
    policy?: string;
    target?: string;
    user?: number;
}

/**
 * A collection of values returned by getPolicyBinding.
 */
export interface GetPolicyBindingResult {
    readonly enabled: boolean;
    readonly failureResult: boolean;
    readonly group: string;
    readonly id: string;
    readonly negate: boolean;
    readonly order: number;
    readonly policy: string;
    readonly target: string;
    readonly timeout: number;
    readonly user: number;
}
export function getPolicyBindingOutput(args?: GetPolicyBindingOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetPolicyBindingResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("authentik:index/getPolicyBinding:getPolicyBinding", {
        "group": args.group,
        "id": args.id,
        "order": args.order,
        "policy": args.policy,
        "target": args.target,
        "user": args.user,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getPolicyBinding.
 */
export interface GetPolicyBindingOutputArgs {
    group?: pulumi.Input<string | undefined>;
    id?: pulumi.Input<string | undefined>;
    order?: pulumi.Input<number | undefined>;
    policy?: pulumi.Input<string | undefined>;
    target?: pulumi.Input<string | undefined>;
    user?: pulumi.Input<number | undefined>;
}
