// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getStagePromptField(args?: GetStagePromptFieldArgs, opts?: pulumi.InvokeOptions): Promise<GetStagePromptFieldResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("authentik:index/getStagePromptField:getStagePromptField", {
        "id": args.id,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getStagePromptField.
 */
export interface GetStagePromptFieldArgs {
    id?: string;
    name?: string;
}

/**
 * A collection of values returned by getStagePromptField.
 */
export interface GetStagePromptFieldResult {
    readonly fieldKey: string;
    readonly id: string;
    readonly initialValue: string;
    readonly initialValueExpression: boolean;
    readonly label: string;
    readonly name: string;
    readonly order: number;
    readonly placeholder: string;
    readonly placeholderExpression: boolean;
    readonly required: boolean;
    readonly subText: string;
    readonly type: string;
}
export function getStagePromptFieldOutput(args?: GetStagePromptFieldOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetStagePromptFieldResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("authentik:index/getStagePromptField:getStagePromptField", {
        "id": args.id,
        "name": args.name,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getStagePromptField.
 */
export interface GetStagePromptFieldOutputArgs {
    id?: pulumi.Input<string | undefined>;
    name?: pulumi.Input<string | undefined>;
}
