// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class OutpostProviderAttachment extends pulumi.CustomResource {
    /**
     * Get an existing OutpostProviderAttachment resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: OutpostProviderAttachmentState, opts?: pulumi.CustomResourceOptions): OutpostProviderAttachment {
        return new OutpostProviderAttachment(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'authentik:index/outpostProviderAttachment:OutpostProviderAttachment';

    /**
     * Returns true if the given object is an instance of OutpostProviderAttachment.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is OutpostProviderAttachment {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === OutpostProviderAttachment.__pulumiType;
    }

    /**
     * The ID of the outpost.
     */
    declare public readonly outpost: pulumi.Output<string>;
    declare public readonly outpostProviderAttachmentId: pulumi.Output<string>;
    /**
     * The ID of the provider.
     */
    declare public readonly protocolProvider: pulumi.Output<number>;

    /**
     * Create a OutpostProviderAttachment resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: OutpostProviderAttachmentArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: OutpostProviderAttachmentArgs | OutpostProviderAttachmentState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as OutpostProviderAttachmentState | undefined;
            resourceInputs["outpost"] = state?.outpost;
            resourceInputs["outpostProviderAttachmentId"] = state?.outpostProviderAttachmentId;
            resourceInputs["protocolProvider"] = state?.protocolProvider;
        } else {
            const args = argsOrState as OutpostProviderAttachmentArgs | undefined;
            if (args?.outpost === undefined && !opts.urn) {
                throw new Error("Missing required property 'outpost'");
            }
            if (args?.protocolProvider === undefined && !opts.urn) {
                throw new Error("Missing required property 'protocolProvider'");
            }
            resourceInputs["outpost"] = args?.outpost;
            resourceInputs["outpostProviderAttachmentId"] = args?.outpostProviderAttachmentId;
            resourceInputs["protocolProvider"] = args?.protocolProvider;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(OutpostProviderAttachment.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering OutpostProviderAttachment resources.
 */
export interface OutpostProviderAttachmentState {
    /**
     * The ID of the outpost.
     */
    outpost?: pulumi.Input<string>;
    outpostProviderAttachmentId?: pulumi.Input<string>;
    /**
     * The ID of the provider.
     */
    protocolProvider?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a OutpostProviderAttachment resource.
 */
export interface OutpostProviderAttachmentArgs {
    /**
     * The ID of the outpost.
     */
    outpost: pulumi.Input<string>;
    outpostProviderAttachmentId?: pulumi.Input<string>;
    /**
     * The ID of the provider.
     */
    protocolProvider: pulumi.Input<number>;
}
