// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class PolicyReputation extends pulumi.CustomResource {
    /**
     * Get an existing PolicyReputation resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: PolicyReputationState, opts?: pulumi.CustomResourceOptions): PolicyReputation {
        return new PolicyReputation(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'authentik:index/policyReputation:PolicyReputation';

    /**
     * Returns true if the given object is an instance of PolicyReputation.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PolicyReputation {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PolicyReputation.__pulumiType;
    }

    /**
     * Defaults to `true`.
     */
    declare public readonly checkIp: pulumi.Output<boolean | undefined>;
    /**
     * Defaults to `true`.
     */
    declare public readonly checkUsername: pulumi.Output<boolean | undefined>;
    /**
     * Defaults to `false`.
     */
    declare public readonly executionLogging: pulumi.Output<boolean | undefined>;
    declare public readonly name: pulumi.Output<string>;
    declare public readonly policyReputationId: pulumi.Output<string>;
    /**
     * Defaults to `10`.
     */
    declare public readonly threshold: pulumi.Output<number | undefined>;

    /**
     * Create a PolicyReputation resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: PolicyReputationArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: PolicyReputationArgs | PolicyReputationState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as PolicyReputationState | undefined;
            resourceInputs["checkIp"] = state?.checkIp;
            resourceInputs["checkUsername"] = state?.checkUsername;
            resourceInputs["executionLogging"] = state?.executionLogging;
            resourceInputs["name"] = state?.name;
            resourceInputs["policyReputationId"] = state?.policyReputationId;
            resourceInputs["threshold"] = state?.threshold;
        } else {
            const args = argsOrState as PolicyReputationArgs | undefined;
            resourceInputs["checkIp"] = args?.checkIp;
            resourceInputs["checkUsername"] = args?.checkUsername;
            resourceInputs["executionLogging"] = args?.executionLogging;
            resourceInputs["name"] = args?.name;
            resourceInputs["policyReputationId"] = args?.policyReputationId;
            resourceInputs["threshold"] = args?.threshold;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(PolicyReputation.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering PolicyReputation resources.
 */
export interface PolicyReputationState {
    /**
     * Defaults to `true`.
     */
    checkIp?: pulumi.Input<boolean>;
    /**
     * Defaults to `true`.
     */
    checkUsername?: pulumi.Input<boolean>;
    /**
     * Defaults to `false`.
     */
    executionLogging?: pulumi.Input<boolean>;
    name?: pulumi.Input<string>;
    policyReputationId?: pulumi.Input<string>;
    /**
     * Defaults to `10`.
     */
    threshold?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a PolicyReputation resource.
 */
export interface PolicyReputationArgs {
    /**
     * Defaults to `true`.
     */
    checkIp?: pulumi.Input<boolean>;
    /**
     * Defaults to `true`.
     */
    checkUsername?: pulumi.Input<boolean>;
    /**
     * Defaults to `false`.
     */
    executionLogging?: pulumi.Input<boolean>;
    name?: pulumi.Input<string>;
    policyReputationId?: pulumi.Input<string>;
    /**
     * Defaults to `10`.
     */
    threshold?: pulumi.Input<number>;
}
