// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class PolicyDummy extends pulumi.CustomResource {
    /**
     * Get an existing PolicyDummy resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: PolicyDummyState, opts?: pulumi.CustomResourceOptions): PolicyDummy {
        return new PolicyDummy(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'authentik:index/policyDummy:PolicyDummy';

    /**
     * Returns true if the given object is an instance of PolicyDummy.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PolicyDummy {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PolicyDummy.__pulumiType;
    }

    /**
     * Defaults to `false`.
     */
    declare public readonly executionLogging: pulumi.Output<boolean | undefined>;
    declare public readonly name: pulumi.Output<string>;
    declare public readonly policyDummyId: pulumi.Output<string>;
    /**
     * Defaults to `false`.
     */
    declare public readonly result: pulumi.Output<boolean | undefined>;
    /**
     * Defaults to `30`.
     */
    declare public readonly waitMax: pulumi.Output<number | undefined>;
    /**
     * Defaults to `5`.
     */
    declare public readonly waitMin: pulumi.Output<number | undefined>;

    /**
     * Create a PolicyDummy resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: PolicyDummyArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: PolicyDummyArgs | PolicyDummyState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as PolicyDummyState | undefined;
            resourceInputs["executionLogging"] = state?.executionLogging;
            resourceInputs["name"] = state?.name;
            resourceInputs["policyDummyId"] = state?.policyDummyId;
            resourceInputs["result"] = state?.result;
            resourceInputs["waitMax"] = state?.waitMax;
            resourceInputs["waitMin"] = state?.waitMin;
        } else {
            const args = argsOrState as PolicyDummyArgs | undefined;
            resourceInputs["executionLogging"] = args?.executionLogging;
            resourceInputs["name"] = args?.name;
            resourceInputs["policyDummyId"] = args?.policyDummyId;
            resourceInputs["result"] = args?.result;
            resourceInputs["waitMax"] = args?.waitMax;
            resourceInputs["waitMin"] = args?.waitMin;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(PolicyDummy.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering PolicyDummy resources.
 */
export interface PolicyDummyState {
    /**
     * Defaults to `false`.
     */
    executionLogging?: pulumi.Input<boolean>;
    name?: pulumi.Input<string>;
    policyDummyId?: pulumi.Input<string>;
    /**
     * Defaults to `false`.
     */
    result?: pulumi.Input<boolean>;
    /**
     * Defaults to `30`.
     */
    waitMax?: pulumi.Input<number>;
    /**
     * Defaults to `5`.
     */
    waitMin?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a PolicyDummy resource.
 */
export interface PolicyDummyArgs {
    /**
     * Defaults to `false`.
     */
    executionLogging?: pulumi.Input<boolean>;
    name?: pulumi.Input<string>;
    policyDummyId?: pulumi.Input<string>;
    /**
     * Defaults to `false`.
     */
    result?: pulumi.Input<boolean>;
    /**
     * Defaults to `30`.
     */
    waitMax?: pulumi.Input<number>;
    /**
     * Defaults to `5`.
     */
    waitMin?: pulumi.Input<number>;
}
