// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class ProviderWsFederation extends pulumi.CustomResource {
    /**
     * Get an existing ProviderWsFederation resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ProviderWsFederationState, opts?: pulumi.CustomResourceOptions): ProviderWsFederation {
        return new ProviderWsFederation(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'authentik:index/providerWsFederation:ProviderWsFederation';

    /**
     * Returns true if the given object is an instance of ProviderWsFederation.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ProviderWsFederation {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ProviderWsFederation.__pulumiType;
    }

    /**
     * Format: hours=1;minutes=2;seconds=3. Defaults to `minutes=-5`.
     */
    declare public readonly assertionValidNotBefore: pulumi.Output<string | undefined>;
    /**
     * Format: hours=1;minutes=2;seconds=3. Defaults to `minutes=5`.
     */
    declare public readonly assertionValidNotOnOrAfter: pulumi.Output<string | undefined>;
    declare public readonly authenticationFlow: pulumi.Output<string | undefined>;
    declare public readonly authnContextClassRefMapping: pulumi.Output<string | undefined>;
    declare public readonly authorizationFlow: pulumi.Output<string>;
    /**
     * Allowed values:
     *   - `http://www.w3.org/2000/09/xmldsig#sha1`
     *   - `http://www.w3.org/2001/04/xmlenc#sha256`
     *   - `http://www.w3.org/2001/04/xmldsig-more#sha384`
     *   - `http://www.w3.org/2001/04/xmlenc#sha512`
     *      Defaults to `http://www.w3.org/2001/04/xmlenc#sha256`.
     */
    declare public readonly digestAlgorithm: pulumi.Output<string | undefined>;
    declare public readonly encryptionKp: pulumi.Output<string | undefined>;
    declare public readonly invalidationFlow: pulumi.Output<string>;
    declare public readonly name: pulumi.Output<string>;
    declare public readonly nameIdMapping: pulumi.Output<string | undefined>;
    declare public readonly propertyMappings: pulumi.Output<string[] | undefined>;
    declare public readonly providerWsFederationId: pulumi.Output<string>;
    declare public readonly replyUrl: pulumi.Output<string>;
    /**
     * Format: hours=1;minutes=2;seconds=3. Defaults to `minutes=86400`.
     */
    declare public readonly sessionValidNotOnOrAfter: pulumi.Output<string | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
     */
    declare public readonly signAssertion: pulumi.Output<boolean | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
     */
    declare public readonly signLogoutRequest: pulumi.Output<boolean | undefined>;
    /**
     * Allowed values:
     *   - `http://www.w3.org/2000/09/xmldsig#rsa-sha1`
     *   - `http://www.w3.org/2001/04/xmldsig-more#rsa-sha256`
     *   - `http://www.w3.org/2001/04/xmldsig-more#rsa-sha384`
     *   - `http://www.w3.org/2001/04/xmldsig-more#rsa-sha512`
     *   - `http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha1`
     *   - `http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha256`
     *   - `http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha384`
     *   - `http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha512`
     *   - `http://www.w3.org/2000/09/xmldsig#dsa-sha1`
     *      Defaults to `http://www.w3.org/2001/04/xmldsig-more#rsa-sha256`.
     */
    declare public readonly signatureAlgorithm: pulumi.Output<string | undefined>;
    declare public readonly signingKp: pulumi.Output<string | undefined>;
    declare public readonly wtrealm: pulumi.Output<string>;

    /**
     * Create a ProviderWsFederation resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ProviderWsFederationArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ProviderWsFederationArgs | ProviderWsFederationState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ProviderWsFederationState | undefined;
            resourceInputs["assertionValidNotBefore"] = state?.assertionValidNotBefore;
            resourceInputs["assertionValidNotOnOrAfter"] = state?.assertionValidNotOnOrAfter;
            resourceInputs["authenticationFlow"] = state?.authenticationFlow;
            resourceInputs["authnContextClassRefMapping"] = state?.authnContextClassRefMapping;
            resourceInputs["authorizationFlow"] = state?.authorizationFlow;
            resourceInputs["digestAlgorithm"] = state?.digestAlgorithm;
            resourceInputs["encryptionKp"] = state?.encryptionKp;
            resourceInputs["invalidationFlow"] = state?.invalidationFlow;
            resourceInputs["name"] = state?.name;
            resourceInputs["nameIdMapping"] = state?.nameIdMapping;
            resourceInputs["propertyMappings"] = state?.propertyMappings;
            resourceInputs["providerWsFederationId"] = state?.providerWsFederationId;
            resourceInputs["replyUrl"] = state?.replyUrl;
            resourceInputs["sessionValidNotOnOrAfter"] = state?.sessionValidNotOnOrAfter;
            resourceInputs["signAssertion"] = state?.signAssertion;
            resourceInputs["signLogoutRequest"] = state?.signLogoutRequest;
            resourceInputs["signatureAlgorithm"] = state?.signatureAlgorithm;
            resourceInputs["signingKp"] = state?.signingKp;
            resourceInputs["wtrealm"] = state?.wtrealm;
        } else {
            const args = argsOrState as ProviderWsFederationArgs | undefined;
            if (args?.authorizationFlow === undefined && !opts.urn) {
                throw new Error("Missing required property 'authorizationFlow'");
            }
            if (args?.invalidationFlow === undefined && !opts.urn) {
                throw new Error("Missing required property 'invalidationFlow'");
            }
            if (args?.replyUrl === undefined && !opts.urn) {
                throw new Error("Missing required property 'replyUrl'");
            }
            if (args?.wtrealm === undefined && !opts.urn) {
                throw new Error("Missing required property 'wtrealm'");
            }
            resourceInputs["assertionValidNotBefore"] = args?.assertionValidNotBefore;
            resourceInputs["assertionValidNotOnOrAfter"] = args?.assertionValidNotOnOrAfter;
            resourceInputs["authenticationFlow"] = args?.authenticationFlow;
            resourceInputs["authnContextClassRefMapping"] = args?.authnContextClassRefMapping;
            resourceInputs["authorizationFlow"] = args?.authorizationFlow;
            resourceInputs["digestAlgorithm"] = args?.digestAlgorithm;
            resourceInputs["encryptionKp"] = args?.encryptionKp;
            resourceInputs["invalidationFlow"] = args?.invalidationFlow;
            resourceInputs["name"] = args?.name;
            resourceInputs["nameIdMapping"] = args?.nameIdMapping;
            resourceInputs["propertyMappings"] = args?.propertyMappings;
            resourceInputs["providerWsFederationId"] = args?.providerWsFederationId;
            resourceInputs["replyUrl"] = args?.replyUrl;
            resourceInputs["sessionValidNotOnOrAfter"] = args?.sessionValidNotOnOrAfter;
            resourceInputs["signAssertion"] = args?.signAssertion;
            resourceInputs["signLogoutRequest"] = args?.signLogoutRequest;
            resourceInputs["signatureAlgorithm"] = args?.signatureAlgorithm;
            resourceInputs["signingKp"] = args?.signingKp;
            resourceInputs["wtrealm"] = args?.wtrealm;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ProviderWsFederation.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering ProviderWsFederation resources.
 */
export interface ProviderWsFederationState {
    /**
     * Format: hours=1;minutes=2;seconds=3. Defaults to `minutes=-5`.
     */
    assertionValidNotBefore?: pulumi.Input<string | undefined>;
    /**
     * Format: hours=1;minutes=2;seconds=3. Defaults to `minutes=5`.
     */
    assertionValidNotOnOrAfter?: pulumi.Input<string | undefined>;
    authenticationFlow?: pulumi.Input<string | undefined>;
    authnContextClassRefMapping?: pulumi.Input<string | undefined>;
    authorizationFlow?: pulumi.Input<string | undefined>;
    /**
     * Allowed values:
     *   - `http://www.w3.org/2000/09/xmldsig#sha1`
     *   - `http://www.w3.org/2001/04/xmlenc#sha256`
     *   - `http://www.w3.org/2001/04/xmldsig-more#sha384`
     *   - `http://www.w3.org/2001/04/xmlenc#sha512`
     *      Defaults to `http://www.w3.org/2001/04/xmlenc#sha256`.
     */
    digestAlgorithm?: pulumi.Input<string | undefined>;
    encryptionKp?: pulumi.Input<string | undefined>;
    invalidationFlow?: pulumi.Input<string | undefined>;
    name?: pulumi.Input<string | undefined>;
    nameIdMapping?: pulumi.Input<string | undefined>;
    propertyMappings?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    providerWsFederationId?: pulumi.Input<string | undefined>;
    replyUrl?: pulumi.Input<string | undefined>;
    /**
     * Format: hours=1;minutes=2;seconds=3. Defaults to `minutes=86400`.
     */
    sessionValidNotOnOrAfter?: pulumi.Input<string | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
     */
    signAssertion?: pulumi.Input<boolean | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
     */
    signLogoutRequest?: pulumi.Input<boolean | undefined>;
    /**
     * Allowed values:
     *   - `http://www.w3.org/2000/09/xmldsig#rsa-sha1`
     *   - `http://www.w3.org/2001/04/xmldsig-more#rsa-sha256`
     *   - `http://www.w3.org/2001/04/xmldsig-more#rsa-sha384`
     *   - `http://www.w3.org/2001/04/xmldsig-more#rsa-sha512`
     *   - `http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha1`
     *   - `http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha256`
     *   - `http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha384`
     *   - `http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha512`
     *   - `http://www.w3.org/2000/09/xmldsig#dsa-sha1`
     *      Defaults to `http://www.w3.org/2001/04/xmldsig-more#rsa-sha256`.
     */
    signatureAlgorithm?: pulumi.Input<string | undefined>;
    signingKp?: pulumi.Input<string | undefined>;
    wtrealm?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a ProviderWsFederation resource.
 */
export interface ProviderWsFederationArgs {
    /**
     * Format: hours=1;minutes=2;seconds=3. Defaults to `minutes=-5`.
     */
    assertionValidNotBefore?: pulumi.Input<string | undefined>;
    /**
     * Format: hours=1;minutes=2;seconds=3. Defaults to `minutes=5`.
     */
    assertionValidNotOnOrAfter?: pulumi.Input<string | undefined>;
    authenticationFlow?: pulumi.Input<string | undefined>;
    authnContextClassRefMapping?: pulumi.Input<string | undefined>;
    authorizationFlow: pulumi.Input<string>;
    /**
     * Allowed values:
     *   - `http://www.w3.org/2000/09/xmldsig#sha1`
     *   - `http://www.w3.org/2001/04/xmlenc#sha256`
     *   - `http://www.w3.org/2001/04/xmldsig-more#sha384`
     *   - `http://www.w3.org/2001/04/xmlenc#sha512`
     *      Defaults to `http://www.w3.org/2001/04/xmlenc#sha256`.
     */
    digestAlgorithm?: pulumi.Input<string | undefined>;
    encryptionKp?: pulumi.Input<string | undefined>;
    invalidationFlow: pulumi.Input<string>;
    name?: pulumi.Input<string | undefined>;
    nameIdMapping?: pulumi.Input<string | undefined>;
    propertyMappings?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    providerWsFederationId?: pulumi.Input<string | undefined>;
    replyUrl: pulumi.Input<string>;
    /**
     * Format: hours=1;minutes=2;seconds=3. Defaults to `minutes=86400`.
     */
    sessionValidNotOnOrAfter?: pulumi.Input<string | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
     */
    signAssertion?: pulumi.Input<boolean | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
     */
    signLogoutRequest?: pulumi.Input<boolean | undefined>;
    /**
     * Allowed values:
     *   - `http://www.w3.org/2000/09/xmldsig#rsa-sha1`
     *   - `http://www.w3.org/2001/04/xmldsig-more#rsa-sha256`
     *   - `http://www.w3.org/2001/04/xmldsig-more#rsa-sha384`
     *   - `http://www.w3.org/2001/04/xmldsig-more#rsa-sha512`
     *   - `http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha1`
     *   - `http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha256`
     *   - `http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha384`
     *   - `http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha512`
     *   - `http://www.w3.org/2000/09/xmldsig#dsa-sha1`
     *      Defaults to `http://www.w3.org/2001/04/xmldsig-more#rsa-sha256`.
     */
    signatureAlgorithm?: pulumi.Input<string | undefined>;
    signingKp?: pulumi.Input<string | undefined>;
    wtrealm: pulumi.Input<string>;
}
