// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class ProviderSaml extends pulumi.CustomResource {
    /**
     * Get an existing ProviderSaml resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ProviderSamlState, opts?: pulumi.CustomResourceOptions): ProviderSaml {
        return new ProviderSaml(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'authentik:index/providerSaml:ProviderSaml';

    /**
     * Returns true if the given object is an instance of ProviderSaml.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ProviderSaml {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ProviderSaml.__pulumiType;
    }

    declare public readonly acsUrl: pulumi.Output<string>;
    /**
     * Format: hours=1;minutes=2;seconds=3. Defaults to `minutes=-5`.
     */
    declare public readonly assertionValidNotBefore: pulumi.Output<string | undefined>;
    /**
     * Format: hours=1;minutes=2;seconds=3. Defaults to `minutes=5`.
     */
    declare public readonly assertionValidNotOnOrAfter: pulumi.Output<string | undefined>;
    /**
     * Defaults to ``.
     */
    declare public readonly audience: pulumi.Output<string | undefined>;
    declare public readonly authenticationFlow: pulumi.Output<string | undefined>;
    declare public readonly authnContextClassRefMapping: pulumi.Output<string | undefined>;
    declare public readonly authorizationFlow: pulumi.Output<string>;
    /**
     * Defaults to ``.
     */
    declare public readonly defaultRelayState: pulumi.Output<string | undefined>;
    /**
     * Allowed values:
     *   - `http://www.w3.org/2000/09/xmldsig#sha1`
     *   - `http://www.w3.org/2001/04/xmlenc#sha256`
     *   - `http://www.w3.org/2001/04/xmldsig-more#sha384`
     *   - `http://www.w3.org/2001/04/xmlenc#sha512`
     *      Defaults to `http://www.w3.org/2001/04/xmlenc#sha256`.
     */
    declare public readonly digestAlgorithm: pulumi.Output<string | undefined>;
    declare public readonly encryptionKp: pulumi.Output<string | undefined>;
    declare public readonly invalidationFlow: pulumi.Output<string>;
    /**
     * Also known as EntityID. Providing a value overrides the default issuer generated by authentik.
     */
    declare public readonly issuerOverride: pulumi.Output<string | undefined>;
    /**
     * Allowed values:
     *   - <span pulumi-lang-nodejs="`frontchannelIframe`" pulumi-lang-dotnet="`FrontchannelIframe`" pulumi-lang-go="`frontchannelIframe`" pulumi-lang-python="`frontchannel_iframe`" pulumi-lang-yaml="`frontchannelIframe`" pulumi-lang-java="`frontchannelIframe`" pulumi-lang-hcl="`frontchannel_iframe`">`frontchannelIframe`</span>
     *   - <span pulumi-lang-nodejs="`frontchannelNative`" pulumi-lang-dotnet="`FrontchannelNative`" pulumi-lang-go="`frontchannelNative`" pulumi-lang-python="`frontchannel_native`" pulumi-lang-yaml="`frontchannelNative`" pulumi-lang-java="`frontchannelNative`" pulumi-lang-hcl="`frontchannel_native`">`frontchannelNative`</span>
     *   - <span pulumi-lang-nodejs="`backchannel`" pulumi-lang-dotnet="`Backchannel`" pulumi-lang-go="`backchannel`" pulumi-lang-python="`backchannel`" pulumi-lang-yaml="`backchannel`" pulumi-lang-java="`backchannel`" pulumi-lang-hcl="`backchannel`">`backchannel`</span>
     *      Defaults to <span pulumi-lang-nodejs="`frontchannelIframe`" pulumi-lang-dotnet="`FrontchannelIframe`" pulumi-lang-go="`frontchannelIframe`" pulumi-lang-python="`frontchannel_iframe`" pulumi-lang-yaml="`frontchannelIframe`" pulumi-lang-java="`frontchannelIframe`" pulumi-lang-hcl="`frontchannel_iframe`">`frontchannelIframe`</span>.
     */
    declare public readonly logoutMethod: pulumi.Output<string | undefined>;
    declare public readonly name: pulumi.Output<string>;
    declare public readonly nameIdMapping: pulumi.Output<string | undefined>;
    declare public readonly propertyMappings: pulumi.Output<string[] | undefined>;
    declare public readonly providerSamlId: pulumi.Output<string>;
    /**
     * Format: hours=1;minutes=2;seconds=3. Defaults to `minutes=86400`.
     */
    declare public readonly sessionValidNotOnOrAfter: pulumi.Output<string | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
     */
    declare public readonly signAssertion: pulumi.Output<boolean | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
     */
    declare public readonly signLogoutRequest: pulumi.Output<boolean | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
     */
    declare public readonly signLogoutResponse: pulumi.Output<boolean | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
     */
    declare public readonly signResponse: pulumi.Output<boolean | undefined>;
    /**
     * Allowed values:
     *   - `http://www.w3.org/2000/09/xmldsig#rsa-sha1`
     *   - `http://www.w3.org/2001/04/xmldsig-more#rsa-sha256`
     *   - `http://www.w3.org/2001/04/xmldsig-more#rsa-sha384`
     *   - `http://www.w3.org/2001/04/xmldsig-more#rsa-sha512`
     *   - `http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha1`
     *   - `http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha256`
     *   - `http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha384`
     *   - `http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha512`
     *   - `http://www.w3.org/2000/09/xmldsig#dsa-sha1`
     *      Defaults to `http://www.w3.org/2001/04/xmldsig-more#rsa-sha256`.
     */
    declare public readonly signatureAlgorithm: pulumi.Output<string | undefined>;
    declare public readonly signingKp: pulumi.Output<string | undefined>;
    /**
     * Allowed values:
     *   - <span pulumi-lang-nodejs="`redirect`" pulumi-lang-dotnet="`Redirect`" pulumi-lang-go="`redirect`" pulumi-lang-python="`redirect`" pulumi-lang-yaml="`redirect`" pulumi-lang-java="`redirect`" pulumi-lang-hcl="`redirect`">`redirect`</span>
     *   - <span pulumi-lang-nodejs="`post`" pulumi-lang-dotnet="`Post`" pulumi-lang-go="`post`" pulumi-lang-python="`post`" pulumi-lang-yaml="`post`" pulumi-lang-java="`post`" pulumi-lang-hcl="`post`">`post`</span>
     *      Defaults to <span pulumi-lang-nodejs="`redirect`" pulumi-lang-dotnet="`Redirect`" pulumi-lang-go="`redirect`" pulumi-lang-python="`redirect`" pulumi-lang-yaml="`redirect`" pulumi-lang-java="`redirect`" pulumi-lang-hcl="`redirect`">`redirect`</span>.
     */
    declare public readonly slsBinding: pulumi.Output<string | undefined>;
    declare public readonly slsUrl: pulumi.Output<string | undefined>;
    /**
     * Allowed values:
     *   - <span pulumi-lang-nodejs="`redirect`" pulumi-lang-dotnet="`Redirect`" pulumi-lang-go="`redirect`" pulumi-lang-python="`redirect`" pulumi-lang-yaml="`redirect`" pulumi-lang-java="`redirect`" pulumi-lang-hcl="`redirect`">`redirect`</span>
     *   - <span pulumi-lang-nodejs="`post`" pulumi-lang-dotnet="`Post`" pulumi-lang-go="`post`" pulumi-lang-python="`post`" pulumi-lang-yaml="`post`" pulumi-lang-java="`post`" pulumi-lang-hcl="`post`">`post`</span>
     *      Defaults to <span pulumi-lang-nodejs="`redirect`" pulumi-lang-dotnet="`Redirect`" pulumi-lang-go="`redirect`" pulumi-lang-python="`redirect`" pulumi-lang-yaml="`redirect`" pulumi-lang-java="`redirect`" pulumi-lang-hcl="`redirect`">`redirect`</span>.
     */
    declare public readonly spBinding: pulumi.Output<string | undefined>;
    /**
     * Generated.
     */
    declare public readonly urlSloPost: pulumi.Output<string>;
    /**
     * Generated.
     */
    declare public readonly urlSloRedirect: pulumi.Output<string>;
    /**
     * Generated.
     */
    declare public readonly urlSsoInit: pulumi.Output<string>;
    /**
     * Generated.
     */
    declare public readonly urlSsoPost: pulumi.Output<string>;
    /**
     * Generated.
     */
    declare public readonly urlSsoRedirect: pulumi.Output<string>;
    declare public readonly verificationKp: pulumi.Output<string | undefined>;

    /**
     * Create a ProviderSaml resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ProviderSamlArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ProviderSamlArgs | ProviderSamlState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ProviderSamlState | undefined;
            resourceInputs["acsUrl"] = state?.acsUrl;
            resourceInputs["assertionValidNotBefore"] = state?.assertionValidNotBefore;
            resourceInputs["assertionValidNotOnOrAfter"] = state?.assertionValidNotOnOrAfter;
            resourceInputs["audience"] = state?.audience;
            resourceInputs["authenticationFlow"] = state?.authenticationFlow;
            resourceInputs["authnContextClassRefMapping"] = state?.authnContextClassRefMapping;
            resourceInputs["authorizationFlow"] = state?.authorizationFlow;
            resourceInputs["defaultRelayState"] = state?.defaultRelayState;
            resourceInputs["digestAlgorithm"] = state?.digestAlgorithm;
            resourceInputs["encryptionKp"] = state?.encryptionKp;
            resourceInputs["invalidationFlow"] = state?.invalidationFlow;
            resourceInputs["issuerOverride"] = state?.issuerOverride;
            resourceInputs["logoutMethod"] = state?.logoutMethod;
            resourceInputs["name"] = state?.name;
            resourceInputs["nameIdMapping"] = state?.nameIdMapping;
            resourceInputs["propertyMappings"] = state?.propertyMappings;
            resourceInputs["providerSamlId"] = state?.providerSamlId;
            resourceInputs["sessionValidNotOnOrAfter"] = state?.sessionValidNotOnOrAfter;
            resourceInputs["signAssertion"] = state?.signAssertion;
            resourceInputs["signLogoutRequest"] = state?.signLogoutRequest;
            resourceInputs["signLogoutResponse"] = state?.signLogoutResponse;
            resourceInputs["signResponse"] = state?.signResponse;
            resourceInputs["signatureAlgorithm"] = state?.signatureAlgorithm;
            resourceInputs["signingKp"] = state?.signingKp;
            resourceInputs["slsBinding"] = state?.slsBinding;
            resourceInputs["slsUrl"] = state?.slsUrl;
            resourceInputs["spBinding"] = state?.spBinding;
            resourceInputs["urlSloPost"] = state?.urlSloPost;
            resourceInputs["urlSloRedirect"] = state?.urlSloRedirect;
            resourceInputs["urlSsoInit"] = state?.urlSsoInit;
            resourceInputs["urlSsoPost"] = state?.urlSsoPost;
            resourceInputs["urlSsoRedirect"] = state?.urlSsoRedirect;
            resourceInputs["verificationKp"] = state?.verificationKp;
        } else {
            const args = argsOrState as ProviderSamlArgs | undefined;
            if (args?.acsUrl === undefined && !opts.urn) {
                throw new Error("Missing required property 'acsUrl'");
            }
            if (args?.authorizationFlow === undefined && !opts.urn) {
                throw new Error("Missing required property 'authorizationFlow'");
            }
            if (args?.invalidationFlow === undefined && !opts.urn) {
                throw new Error("Missing required property 'invalidationFlow'");
            }
            resourceInputs["acsUrl"] = args?.acsUrl;
            resourceInputs["assertionValidNotBefore"] = args?.assertionValidNotBefore;
            resourceInputs["assertionValidNotOnOrAfter"] = args?.assertionValidNotOnOrAfter;
            resourceInputs["audience"] = args?.audience;
            resourceInputs["authenticationFlow"] = args?.authenticationFlow;
            resourceInputs["authnContextClassRefMapping"] = args?.authnContextClassRefMapping;
            resourceInputs["authorizationFlow"] = args?.authorizationFlow;
            resourceInputs["defaultRelayState"] = args?.defaultRelayState;
            resourceInputs["digestAlgorithm"] = args?.digestAlgorithm;
            resourceInputs["encryptionKp"] = args?.encryptionKp;
            resourceInputs["invalidationFlow"] = args?.invalidationFlow;
            resourceInputs["issuerOverride"] = args?.issuerOverride;
            resourceInputs["logoutMethod"] = args?.logoutMethod;
            resourceInputs["name"] = args?.name;
            resourceInputs["nameIdMapping"] = args?.nameIdMapping;
            resourceInputs["propertyMappings"] = args?.propertyMappings;
            resourceInputs["providerSamlId"] = args?.providerSamlId;
            resourceInputs["sessionValidNotOnOrAfter"] = args?.sessionValidNotOnOrAfter;
            resourceInputs["signAssertion"] = args?.signAssertion;
            resourceInputs["signLogoutRequest"] = args?.signLogoutRequest;
            resourceInputs["signLogoutResponse"] = args?.signLogoutResponse;
            resourceInputs["signResponse"] = args?.signResponse;
            resourceInputs["signatureAlgorithm"] = args?.signatureAlgorithm;
            resourceInputs["signingKp"] = args?.signingKp;
            resourceInputs["slsBinding"] = args?.slsBinding;
            resourceInputs["slsUrl"] = args?.slsUrl;
            resourceInputs["spBinding"] = args?.spBinding;
            resourceInputs["urlSloPost"] = args?.urlSloPost;
            resourceInputs["urlSloRedirect"] = args?.urlSloRedirect;
            resourceInputs["urlSsoInit"] = args?.urlSsoInit;
            resourceInputs["urlSsoPost"] = args?.urlSsoPost;
            resourceInputs["urlSsoRedirect"] = args?.urlSsoRedirect;
            resourceInputs["verificationKp"] = args?.verificationKp;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(ProviderSaml.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering ProviderSaml resources.
 */
export interface ProviderSamlState {
    acsUrl?: pulumi.Input<string | undefined>;
    /**
     * Format: hours=1;minutes=2;seconds=3. Defaults to `minutes=-5`.
     */
    assertionValidNotBefore?: pulumi.Input<string | undefined>;
    /**
     * Format: hours=1;minutes=2;seconds=3. Defaults to `minutes=5`.
     */
    assertionValidNotOnOrAfter?: pulumi.Input<string | undefined>;
    /**
     * Defaults to ``.
     */
    audience?: pulumi.Input<string | undefined>;
    authenticationFlow?: pulumi.Input<string | undefined>;
    authnContextClassRefMapping?: pulumi.Input<string | undefined>;
    authorizationFlow?: pulumi.Input<string | undefined>;
    /**
     * Defaults to ``.
     */
    defaultRelayState?: pulumi.Input<string | undefined>;
    /**
     * Allowed values:
     *   - `http://www.w3.org/2000/09/xmldsig#sha1`
     *   - `http://www.w3.org/2001/04/xmlenc#sha256`
     *   - `http://www.w3.org/2001/04/xmldsig-more#sha384`
     *   - `http://www.w3.org/2001/04/xmlenc#sha512`
     *      Defaults to `http://www.w3.org/2001/04/xmlenc#sha256`.
     */
    digestAlgorithm?: pulumi.Input<string | undefined>;
    encryptionKp?: pulumi.Input<string | undefined>;
    invalidationFlow?: pulumi.Input<string | undefined>;
    /**
     * Also known as EntityID. Providing a value overrides the default issuer generated by authentik.
     */
    issuerOverride?: pulumi.Input<string | undefined>;
    /**
     * Allowed values:
     *   - <span pulumi-lang-nodejs="`frontchannelIframe`" pulumi-lang-dotnet="`FrontchannelIframe`" pulumi-lang-go="`frontchannelIframe`" pulumi-lang-python="`frontchannel_iframe`" pulumi-lang-yaml="`frontchannelIframe`" pulumi-lang-java="`frontchannelIframe`" pulumi-lang-hcl="`frontchannel_iframe`">`frontchannelIframe`</span>
     *   - <span pulumi-lang-nodejs="`frontchannelNative`" pulumi-lang-dotnet="`FrontchannelNative`" pulumi-lang-go="`frontchannelNative`" pulumi-lang-python="`frontchannel_native`" pulumi-lang-yaml="`frontchannelNative`" pulumi-lang-java="`frontchannelNative`" pulumi-lang-hcl="`frontchannel_native`">`frontchannelNative`</span>
     *   - <span pulumi-lang-nodejs="`backchannel`" pulumi-lang-dotnet="`Backchannel`" pulumi-lang-go="`backchannel`" pulumi-lang-python="`backchannel`" pulumi-lang-yaml="`backchannel`" pulumi-lang-java="`backchannel`" pulumi-lang-hcl="`backchannel`">`backchannel`</span>
     *      Defaults to <span pulumi-lang-nodejs="`frontchannelIframe`" pulumi-lang-dotnet="`FrontchannelIframe`" pulumi-lang-go="`frontchannelIframe`" pulumi-lang-python="`frontchannel_iframe`" pulumi-lang-yaml="`frontchannelIframe`" pulumi-lang-java="`frontchannelIframe`" pulumi-lang-hcl="`frontchannel_iframe`">`frontchannelIframe`</span>.
     */
    logoutMethod?: pulumi.Input<string | undefined>;
    name?: pulumi.Input<string | undefined>;
    nameIdMapping?: pulumi.Input<string | undefined>;
    propertyMappings?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    providerSamlId?: pulumi.Input<string | undefined>;
    /**
     * Format: hours=1;minutes=2;seconds=3. Defaults to `minutes=86400`.
     */
    sessionValidNotOnOrAfter?: pulumi.Input<string | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
     */
    signAssertion?: pulumi.Input<boolean | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
     */
    signLogoutRequest?: pulumi.Input<boolean | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
     */
    signLogoutResponse?: pulumi.Input<boolean | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
     */
    signResponse?: pulumi.Input<boolean | undefined>;
    /**
     * Allowed values:
     *   - `http://www.w3.org/2000/09/xmldsig#rsa-sha1`
     *   - `http://www.w3.org/2001/04/xmldsig-more#rsa-sha256`
     *   - `http://www.w3.org/2001/04/xmldsig-more#rsa-sha384`
     *   - `http://www.w3.org/2001/04/xmldsig-more#rsa-sha512`
     *   - `http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha1`
     *   - `http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha256`
     *   - `http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha384`
     *   - `http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha512`
     *   - `http://www.w3.org/2000/09/xmldsig#dsa-sha1`
     *      Defaults to `http://www.w3.org/2001/04/xmldsig-more#rsa-sha256`.
     */
    signatureAlgorithm?: pulumi.Input<string | undefined>;
    signingKp?: pulumi.Input<string | undefined>;
    /**
     * Allowed values:
     *   - <span pulumi-lang-nodejs="`redirect`" pulumi-lang-dotnet="`Redirect`" pulumi-lang-go="`redirect`" pulumi-lang-python="`redirect`" pulumi-lang-yaml="`redirect`" pulumi-lang-java="`redirect`" pulumi-lang-hcl="`redirect`">`redirect`</span>
     *   - <span pulumi-lang-nodejs="`post`" pulumi-lang-dotnet="`Post`" pulumi-lang-go="`post`" pulumi-lang-python="`post`" pulumi-lang-yaml="`post`" pulumi-lang-java="`post`" pulumi-lang-hcl="`post`">`post`</span>
     *      Defaults to <span pulumi-lang-nodejs="`redirect`" pulumi-lang-dotnet="`Redirect`" pulumi-lang-go="`redirect`" pulumi-lang-python="`redirect`" pulumi-lang-yaml="`redirect`" pulumi-lang-java="`redirect`" pulumi-lang-hcl="`redirect`">`redirect`</span>.
     */
    slsBinding?: pulumi.Input<string | undefined>;
    slsUrl?: pulumi.Input<string | undefined>;
    /**
     * Allowed values:
     *   - <span pulumi-lang-nodejs="`redirect`" pulumi-lang-dotnet="`Redirect`" pulumi-lang-go="`redirect`" pulumi-lang-python="`redirect`" pulumi-lang-yaml="`redirect`" pulumi-lang-java="`redirect`" pulumi-lang-hcl="`redirect`">`redirect`</span>
     *   - <span pulumi-lang-nodejs="`post`" pulumi-lang-dotnet="`Post`" pulumi-lang-go="`post`" pulumi-lang-python="`post`" pulumi-lang-yaml="`post`" pulumi-lang-java="`post`" pulumi-lang-hcl="`post`">`post`</span>
     *      Defaults to <span pulumi-lang-nodejs="`redirect`" pulumi-lang-dotnet="`Redirect`" pulumi-lang-go="`redirect`" pulumi-lang-python="`redirect`" pulumi-lang-yaml="`redirect`" pulumi-lang-java="`redirect`" pulumi-lang-hcl="`redirect`">`redirect`</span>.
     */
    spBinding?: pulumi.Input<string | undefined>;
    /**
     * Generated.
     */
    urlSloPost?: pulumi.Input<string | undefined>;
    /**
     * Generated.
     */
    urlSloRedirect?: pulumi.Input<string | undefined>;
    /**
     * Generated.
     */
    urlSsoInit?: pulumi.Input<string | undefined>;
    /**
     * Generated.
     */
    urlSsoPost?: pulumi.Input<string | undefined>;
    /**
     * Generated.
     */
    urlSsoRedirect?: pulumi.Input<string | undefined>;
    verificationKp?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a ProviderSaml resource.
 */
export interface ProviderSamlArgs {
    acsUrl: pulumi.Input<string>;
    /**
     * Format: hours=1;minutes=2;seconds=3. Defaults to `minutes=-5`.
     */
    assertionValidNotBefore?: pulumi.Input<string | undefined>;
    /**
     * Format: hours=1;minutes=2;seconds=3. Defaults to `minutes=5`.
     */
    assertionValidNotOnOrAfter?: pulumi.Input<string | undefined>;
    /**
     * Defaults to ``.
     */
    audience?: pulumi.Input<string | undefined>;
    authenticationFlow?: pulumi.Input<string | undefined>;
    authnContextClassRefMapping?: pulumi.Input<string | undefined>;
    authorizationFlow: pulumi.Input<string>;
    /**
     * Defaults to ``.
     */
    defaultRelayState?: pulumi.Input<string | undefined>;
    /**
     * Allowed values:
     *   - `http://www.w3.org/2000/09/xmldsig#sha1`
     *   - `http://www.w3.org/2001/04/xmlenc#sha256`
     *   - `http://www.w3.org/2001/04/xmldsig-more#sha384`
     *   - `http://www.w3.org/2001/04/xmlenc#sha512`
     *      Defaults to `http://www.w3.org/2001/04/xmlenc#sha256`.
     */
    digestAlgorithm?: pulumi.Input<string | undefined>;
    encryptionKp?: pulumi.Input<string | undefined>;
    invalidationFlow: pulumi.Input<string>;
    /**
     * Also known as EntityID. Providing a value overrides the default issuer generated by authentik.
     */
    issuerOverride?: pulumi.Input<string | undefined>;
    /**
     * Allowed values:
     *   - <span pulumi-lang-nodejs="`frontchannelIframe`" pulumi-lang-dotnet="`FrontchannelIframe`" pulumi-lang-go="`frontchannelIframe`" pulumi-lang-python="`frontchannel_iframe`" pulumi-lang-yaml="`frontchannelIframe`" pulumi-lang-java="`frontchannelIframe`" pulumi-lang-hcl="`frontchannel_iframe`">`frontchannelIframe`</span>
     *   - <span pulumi-lang-nodejs="`frontchannelNative`" pulumi-lang-dotnet="`FrontchannelNative`" pulumi-lang-go="`frontchannelNative`" pulumi-lang-python="`frontchannel_native`" pulumi-lang-yaml="`frontchannelNative`" pulumi-lang-java="`frontchannelNative`" pulumi-lang-hcl="`frontchannel_native`">`frontchannelNative`</span>
     *   - <span pulumi-lang-nodejs="`backchannel`" pulumi-lang-dotnet="`Backchannel`" pulumi-lang-go="`backchannel`" pulumi-lang-python="`backchannel`" pulumi-lang-yaml="`backchannel`" pulumi-lang-java="`backchannel`" pulumi-lang-hcl="`backchannel`">`backchannel`</span>
     *      Defaults to <span pulumi-lang-nodejs="`frontchannelIframe`" pulumi-lang-dotnet="`FrontchannelIframe`" pulumi-lang-go="`frontchannelIframe`" pulumi-lang-python="`frontchannel_iframe`" pulumi-lang-yaml="`frontchannelIframe`" pulumi-lang-java="`frontchannelIframe`" pulumi-lang-hcl="`frontchannel_iframe`">`frontchannelIframe`</span>.
     */
    logoutMethod?: pulumi.Input<string | undefined>;
    name?: pulumi.Input<string | undefined>;
    nameIdMapping?: pulumi.Input<string | undefined>;
    propertyMappings?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    providerSamlId?: pulumi.Input<string | undefined>;
    /**
     * Format: hours=1;minutes=2;seconds=3. Defaults to `minutes=86400`.
     */
    sessionValidNotOnOrAfter?: pulumi.Input<string | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
     */
    signAssertion?: pulumi.Input<boolean | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
     */
    signLogoutRequest?: pulumi.Input<boolean | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
     */
    signLogoutResponse?: pulumi.Input<boolean | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
     */
    signResponse?: pulumi.Input<boolean | undefined>;
    /**
     * Allowed values:
     *   - `http://www.w3.org/2000/09/xmldsig#rsa-sha1`
     *   - `http://www.w3.org/2001/04/xmldsig-more#rsa-sha256`
     *   - `http://www.w3.org/2001/04/xmldsig-more#rsa-sha384`
     *   - `http://www.w3.org/2001/04/xmldsig-more#rsa-sha512`
     *   - `http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha1`
     *   - `http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha256`
     *   - `http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha384`
     *   - `http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha512`
     *   - `http://www.w3.org/2000/09/xmldsig#dsa-sha1`
     *      Defaults to `http://www.w3.org/2001/04/xmldsig-more#rsa-sha256`.
     */
    signatureAlgorithm?: pulumi.Input<string | undefined>;
    signingKp?: pulumi.Input<string | undefined>;
    /**
     * Allowed values:
     *   - <span pulumi-lang-nodejs="`redirect`" pulumi-lang-dotnet="`Redirect`" pulumi-lang-go="`redirect`" pulumi-lang-python="`redirect`" pulumi-lang-yaml="`redirect`" pulumi-lang-java="`redirect`" pulumi-lang-hcl="`redirect`">`redirect`</span>
     *   - <span pulumi-lang-nodejs="`post`" pulumi-lang-dotnet="`Post`" pulumi-lang-go="`post`" pulumi-lang-python="`post`" pulumi-lang-yaml="`post`" pulumi-lang-java="`post`" pulumi-lang-hcl="`post`">`post`</span>
     *      Defaults to <span pulumi-lang-nodejs="`redirect`" pulumi-lang-dotnet="`Redirect`" pulumi-lang-go="`redirect`" pulumi-lang-python="`redirect`" pulumi-lang-yaml="`redirect`" pulumi-lang-java="`redirect`" pulumi-lang-hcl="`redirect`">`redirect`</span>.
     */
    slsBinding?: pulumi.Input<string | undefined>;
    slsUrl?: pulumi.Input<string | undefined>;
    /**
     * Allowed values:
     *   - <span pulumi-lang-nodejs="`redirect`" pulumi-lang-dotnet="`Redirect`" pulumi-lang-go="`redirect`" pulumi-lang-python="`redirect`" pulumi-lang-yaml="`redirect`" pulumi-lang-java="`redirect`" pulumi-lang-hcl="`redirect`">`redirect`</span>
     *   - <span pulumi-lang-nodejs="`post`" pulumi-lang-dotnet="`Post`" pulumi-lang-go="`post`" pulumi-lang-python="`post`" pulumi-lang-yaml="`post`" pulumi-lang-java="`post`" pulumi-lang-hcl="`post`">`post`</span>
     *      Defaults to <span pulumi-lang-nodejs="`redirect`" pulumi-lang-dotnet="`Redirect`" pulumi-lang-go="`redirect`" pulumi-lang-python="`redirect`" pulumi-lang-yaml="`redirect`" pulumi-lang-java="`redirect`" pulumi-lang-hcl="`redirect`">`redirect`</span>.
     */
    spBinding?: pulumi.Input<string | undefined>;
    /**
     * Generated.
     */
    urlSloPost?: pulumi.Input<string | undefined>;
    /**
     * Generated.
     */
    urlSloRedirect?: pulumi.Input<string | undefined>;
    /**
     * Generated.
     */
    urlSsoInit?: pulumi.Input<string | undefined>;
    /**
     * Generated.
     */
    urlSsoPost?: pulumi.Input<string | undefined>;
    /**
     * Generated.
     */
    urlSsoRedirect?: pulumi.Input<string | undefined>;
    verificationKp?: pulumi.Input<string | undefined>;
}
