// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class SourceSaml extends pulumi.CustomResource {
    /**
     * Get an existing SourceSaml resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SourceSamlState, opts?: pulumi.CustomResourceOptions): SourceSaml {
        return new SourceSaml(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'authentik:index/sourceSaml:SourceSaml';

    /**
     * Returns true if the given object is an instance of SourceSaml.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SourceSaml {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SourceSaml.__pulumiType;
    }

    /**
     * Defaults to `false`.
     */
    declare public readonly allowIdpInitiated: pulumi.Output<boolean | undefined>;
    declare public readonly authenticationFlow: pulumi.Output<string | undefined>;
    /**
     * Allowed values: - `REDIRECT` - `POST` - `POST_AUTO` Defaults to `REDIRECT`.
     */
    declare public readonly bindingType: pulumi.Output<string | undefined>;
    /**
     * Allowed values: - `http://www.w3.org/2000/09/xmldsig#sha1` - `http://www.w3.org/2001/04/xmlenc#sha256` -
     * `http://www.w3.org/2001/04/xmldsig-more#sha384` - `http://www.w3.org/2001/04/xmlenc#sha512` Defaults to
     * `http://www.w3.org/2001/04/xmlenc#sha256`.
     */
    declare public readonly digestAlgorithm: pulumi.Output<string | undefined>;
    /**
     * Defaults to `true`.
     */
    declare public readonly enabled: pulumi.Output<boolean | undefined>;
    declare public readonly encryptionKp: pulumi.Output<string | undefined>;
    declare public readonly enrollmentFlow: pulumi.Output<string | undefined>;
    /**
     * Allowed values: - `identifier` - `name_link` - `name_deny` Defaults to `identifier`.
     */
    declare public readonly groupMatchingMode: pulumi.Output<string | undefined>;
    declare public readonly issuer: pulumi.Output<string | undefined>;
    /**
     * SAML Metadata Generated.
     */
    declare public /*out*/ readonly metadata: pulumi.Output<string>;
    declare public readonly name: pulumi.Output<string>;
    /**
     * Allowed values: - `urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress` -
     * `urn:oasis:names:tc:SAML:2.0:nameid-format:persistent` - `urn:oasis:names:tc:SAML:1.1:nameid-format:X509SubjectName` -
     * `urn:oasis:names:tc:SAML:2.0:nameid-format:WindowsDomainQualifiedName` -
     * `urn:oasis:names:tc:SAML:2.0:nameid-format:transient` - `urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified` Defaults
     * to `urn:oasis:names:tc:SAML:2.0:nameid-format:persistent`.
     */
    declare public readonly nameIdPolicy: pulumi.Output<string | undefined>;
    /**
     * Allowed values: - `all` - `any` Defaults to `any`.
     */
    declare public readonly policyEngineMode: pulumi.Output<string | undefined>;
    declare public readonly preAuthenticationFlow: pulumi.Output<string>;
    /**
     * Allowed values: - `http://www.w3.org/2000/09/xmldsig#rsa-sha1` - `http://www.w3.org/2001/04/xmldsig-more#rsa-sha256` -
     * `http://www.w3.org/2001/04/xmldsig-more#rsa-sha384` - `http://www.w3.org/2001/04/xmldsig-more#rsa-sha512` -
     * `http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha1` - `http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha256` -
     * `http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha384` - `http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha512` -
     * `http://www.w3.org/2000/09/xmldsig#dsa-sha1` Defaults to `http://www.w3.org/2001/04/xmldsig-more#rsa-sha256`.
     */
    declare public readonly signatureAlgorithm: pulumi.Output<string | undefined>;
    declare public readonly signingKp: pulumi.Output<string | undefined>;
    declare public readonly sloUrl: pulumi.Output<string | undefined>;
    declare public readonly slug: pulumi.Output<string>;
    declare public readonly sourceSamlId: pulumi.Output<string>;
    declare public readonly ssoUrl: pulumi.Output<string>;
    /**
     * Format: hours=1;minutes=2;seconds=3. Defaults to `days=1`.
     */
    declare public readonly temporaryUserDeleteAfter: pulumi.Output<string | undefined>;
    /**
     * Allowed values: - `identifier` - `email_link` - `email_deny` - `username_link` - `username_deny` Defaults to
     * `identifier`.
     */
    declare public readonly userMatchingMode: pulumi.Output<string | undefined>;
    /**
     * Defaults to `goauthentik.io/sources/%(slug)s`.
     */
    declare public readonly userPathTemplate: pulumi.Output<string | undefined>;
    /**
     * Generated.
     */
    declare public readonly uuid: pulumi.Output<string>;
    declare public readonly verificationKp: pulumi.Output<string | undefined>;

    /**
     * Create a SourceSaml resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: SourceSamlArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SourceSamlArgs | SourceSamlState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SourceSamlState | undefined;
            resourceInputs["allowIdpInitiated"] = state?.allowIdpInitiated;
            resourceInputs["authenticationFlow"] = state?.authenticationFlow;
            resourceInputs["bindingType"] = state?.bindingType;
            resourceInputs["digestAlgorithm"] = state?.digestAlgorithm;
            resourceInputs["enabled"] = state?.enabled;
            resourceInputs["encryptionKp"] = state?.encryptionKp;
            resourceInputs["enrollmentFlow"] = state?.enrollmentFlow;
            resourceInputs["groupMatchingMode"] = state?.groupMatchingMode;
            resourceInputs["issuer"] = state?.issuer;
            resourceInputs["metadata"] = state?.metadata;
            resourceInputs["name"] = state?.name;
            resourceInputs["nameIdPolicy"] = state?.nameIdPolicy;
            resourceInputs["policyEngineMode"] = state?.policyEngineMode;
            resourceInputs["preAuthenticationFlow"] = state?.preAuthenticationFlow;
            resourceInputs["signatureAlgorithm"] = state?.signatureAlgorithm;
            resourceInputs["signingKp"] = state?.signingKp;
            resourceInputs["sloUrl"] = state?.sloUrl;
            resourceInputs["slug"] = state?.slug;
            resourceInputs["sourceSamlId"] = state?.sourceSamlId;
            resourceInputs["ssoUrl"] = state?.ssoUrl;
            resourceInputs["temporaryUserDeleteAfter"] = state?.temporaryUserDeleteAfter;
            resourceInputs["userMatchingMode"] = state?.userMatchingMode;
            resourceInputs["userPathTemplate"] = state?.userPathTemplate;
            resourceInputs["uuid"] = state?.uuid;
            resourceInputs["verificationKp"] = state?.verificationKp;
        } else {
            const args = argsOrState as SourceSamlArgs | undefined;
            if (args?.preAuthenticationFlow === undefined && !opts.urn) {
                throw new Error("Missing required property 'preAuthenticationFlow'");
            }
            if (args?.slug === undefined && !opts.urn) {
                throw new Error("Missing required property 'slug'");
            }
            if (args?.ssoUrl === undefined && !opts.urn) {
                throw new Error("Missing required property 'ssoUrl'");
            }
            resourceInputs["allowIdpInitiated"] = args?.allowIdpInitiated;
            resourceInputs["authenticationFlow"] = args?.authenticationFlow;
            resourceInputs["bindingType"] = args?.bindingType;
            resourceInputs["digestAlgorithm"] = args?.digestAlgorithm;
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["encryptionKp"] = args?.encryptionKp;
            resourceInputs["enrollmentFlow"] = args?.enrollmentFlow;
            resourceInputs["groupMatchingMode"] = args?.groupMatchingMode;
            resourceInputs["issuer"] = args?.issuer;
            resourceInputs["name"] = args?.name;
            resourceInputs["nameIdPolicy"] = args?.nameIdPolicy;
            resourceInputs["policyEngineMode"] = args?.policyEngineMode;
            resourceInputs["preAuthenticationFlow"] = args?.preAuthenticationFlow;
            resourceInputs["signatureAlgorithm"] = args?.signatureAlgorithm;
            resourceInputs["signingKp"] = args?.signingKp;
            resourceInputs["sloUrl"] = args?.sloUrl;
            resourceInputs["slug"] = args?.slug;
            resourceInputs["sourceSamlId"] = args?.sourceSamlId;
            resourceInputs["ssoUrl"] = args?.ssoUrl;
            resourceInputs["temporaryUserDeleteAfter"] = args?.temporaryUserDeleteAfter;
            resourceInputs["userMatchingMode"] = args?.userMatchingMode;
            resourceInputs["userPathTemplate"] = args?.userPathTemplate;
            resourceInputs["uuid"] = args?.uuid;
            resourceInputs["verificationKp"] = args?.verificationKp;
            resourceInputs["metadata"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SourceSaml.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering SourceSaml resources.
 */
export interface SourceSamlState {
    /**
     * Defaults to `false`.
     */
    allowIdpInitiated?: pulumi.Input<boolean>;
    authenticationFlow?: pulumi.Input<string>;
    /**
     * Allowed values: - `REDIRECT` - `POST` - `POST_AUTO` Defaults to `REDIRECT`.
     */
    bindingType?: pulumi.Input<string>;
    /**
     * Allowed values: - `http://www.w3.org/2000/09/xmldsig#sha1` - `http://www.w3.org/2001/04/xmlenc#sha256` -
     * `http://www.w3.org/2001/04/xmldsig-more#sha384` - `http://www.w3.org/2001/04/xmlenc#sha512` Defaults to
     * `http://www.w3.org/2001/04/xmlenc#sha256`.
     */
    digestAlgorithm?: pulumi.Input<string>;
    /**
     * Defaults to `true`.
     */
    enabled?: pulumi.Input<boolean>;
    encryptionKp?: pulumi.Input<string>;
    enrollmentFlow?: pulumi.Input<string>;
    /**
     * Allowed values: - `identifier` - `name_link` - `name_deny` Defaults to `identifier`.
     */
    groupMatchingMode?: pulumi.Input<string>;
    issuer?: pulumi.Input<string>;
    /**
     * SAML Metadata Generated.
     */
    metadata?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    /**
     * Allowed values: - `urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress` -
     * `urn:oasis:names:tc:SAML:2.0:nameid-format:persistent` - `urn:oasis:names:tc:SAML:1.1:nameid-format:X509SubjectName` -
     * `urn:oasis:names:tc:SAML:2.0:nameid-format:WindowsDomainQualifiedName` -
     * `urn:oasis:names:tc:SAML:2.0:nameid-format:transient` - `urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified` Defaults
     * to `urn:oasis:names:tc:SAML:2.0:nameid-format:persistent`.
     */
    nameIdPolicy?: pulumi.Input<string>;
    /**
     * Allowed values: - `all` - `any` Defaults to `any`.
     */
    policyEngineMode?: pulumi.Input<string>;
    preAuthenticationFlow?: pulumi.Input<string>;
    /**
     * Allowed values: - `http://www.w3.org/2000/09/xmldsig#rsa-sha1` - `http://www.w3.org/2001/04/xmldsig-more#rsa-sha256` -
     * `http://www.w3.org/2001/04/xmldsig-more#rsa-sha384` - `http://www.w3.org/2001/04/xmldsig-more#rsa-sha512` -
     * `http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha1` - `http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha256` -
     * `http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha384` - `http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha512` -
     * `http://www.w3.org/2000/09/xmldsig#dsa-sha1` Defaults to `http://www.w3.org/2001/04/xmldsig-more#rsa-sha256`.
     */
    signatureAlgorithm?: pulumi.Input<string>;
    signingKp?: pulumi.Input<string>;
    sloUrl?: pulumi.Input<string>;
    slug?: pulumi.Input<string>;
    sourceSamlId?: pulumi.Input<string>;
    ssoUrl?: pulumi.Input<string>;
    /**
     * Format: hours=1;minutes=2;seconds=3. Defaults to `days=1`.
     */
    temporaryUserDeleteAfter?: pulumi.Input<string>;
    /**
     * Allowed values: - `identifier` - `email_link` - `email_deny` - `username_link` - `username_deny` Defaults to
     * `identifier`.
     */
    userMatchingMode?: pulumi.Input<string>;
    /**
     * Defaults to `goauthentik.io/sources/%(slug)s`.
     */
    userPathTemplate?: pulumi.Input<string>;
    /**
     * Generated.
     */
    uuid?: pulumi.Input<string>;
    verificationKp?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a SourceSaml resource.
 */
export interface SourceSamlArgs {
    /**
     * Defaults to `false`.
     */
    allowIdpInitiated?: pulumi.Input<boolean>;
    authenticationFlow?: pulumi.Input<string>;
    /**
     * Allowed values: - `REDIRECT` - `POST` - `POST_AUTO` Defaults to `REDIRECT`.
     */
    bindingType?: pulumi.Input<string>;
    /**
     * Allowed values: - `http://www.w3.org/2000/09/xmldsig#sha1` - `http://www.w3.org/2001/04/xmlenc#sha256` -
     * `http://www.w3.org/2001/04/xmldsig-more#sha384` - `http://www.w3.org/2001/04/xmlenc#sha512` Defaults to
     * `http://www.w3.org/2001/04/xmlenc#sha256`.
     */
    digestAlgorithm?: pulumi.Input<string>;
    /**
     * Defaults to `true`.
     */
    enabled?: pulumi.Input<boolean>;
    encryptionKp?: pulumi.Input<string>;
    enrollmentFlow?: pulumi.Input<string>;
    /**
     * Allowed values: - `identifier` - `name_link` - `name_deny` Defaults to `identifier`.
     */
    groupMatchingMode?: pulumi.Input<string>;
    issuer?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    /**
     * Allowed values: - `urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress` -
     * `urn:oasis:names:tc:SAML:2.0:nameid-format:persistent` - `urn:oasis:names:tc:SAML:1.1:nameid-format:X509SubjectName` -
     * `urn:oasis:names:tc:SAML:2.0:nameid-format:WindowsDomainQualifiedName` -
     * `urn:oasis:names:tc:SAML:2.0:nameid-format:transient` - `urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified` Defaults
     * to `urn:oasis:names:tc:SAML:2.0:nameid-format:persistent`.
     */
    nameIdPolicy?: pulumi.Input<string>;
    /**
     * Allowed values: - `all` - `any` Defaults to `any`.
     */
    policyEngineMode?: pulumi.Input<string>;
    preAuthenticationFlow: pulumi.Input<string>;
    /**
     * Allowed values: - `http://www.w3.org/2000/09/xmldsig#rsa-sha1` - `http://www.w3.org/2001/04/xmldsig-more#rsa-sha256` -
     * `http://www.w3.org/2001/04/xmldsig-more#rsa-sha384` - `http://www.w3.org/2001/04/xmldsig-more#rsa-sha512` -
     * `http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha1` - `http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha256` -
     * `http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha384` - `http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha512` -
     * `http://www.w3.org/2000/09/xmldsig#dsa-sha1` Defaults to `http://www.w3.org/2001/04/xmldsig-more#rsa-sha256`.
     */
    signatureAlgorithm?: pulumi.Input<string>;
    signingKp?: pulumi.Input<string>;
    sloUrl?: pulumi.Input<string>;
    slug: pulumi.Input<string>;
    sourceSamlId?: pulumi.Input<string>;
    ssoUrl: pulumi.Input<string>;
    /**
     * Format: hours=1;minutes=2;seconds=3. Defaults to `days=1`.
     */
    temporaryUserDeleteAfter?: pulumi.Input<string>;
    /**
     * Allowed values: - `identifier` - `email_link` - `email_deny` - `username_link` - `username_deny` Defaults to
     * `identifier`.
     */
    userMatchingMode?: pulumi.Input<string>;
    /**
     * Defaults to `goauthentik.io/sources/%(slug)s`.
     */
    userPathTemplate?: pulumi.Input<string>;
    /**
     * Generated.
     */
    uuid?: pulumi.Input<string>;
    verificationKp?: pulumi.Input<string>;
}
