// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class StageUserLogin extends pulumi.CustomResource {
    /**
     * Get an existing StageUserLogin resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: StageUserLoginState, opts?: pulumi.CustomResourceOptions): StageUserLogin {
        return new StageUserLogin(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'authentik:index/stageUserLogin:StageUserLogin';

    /**
     * Returns true if the given object is an instance of StageUserLogin.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is StageUserLogin {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === StageUserLogin.__pulumiType;
    }

    /**
     * Allowed values: - `no_binding` - `bind_continent` - `bind_continent_country` - `bind_continent_country_city` Defaults to
     * `no_binding`.
     */
    declare public readonly geoipBinding: pulumi.Output<string | undefined>;
    declare public readonly name: pulumi.Output<string>;
    /**
     * Allowed values: - `no_binding` - `bind_asn` - `bind_asn_network` - `bind_asn_network_ip` Defaults to `no_binding`.
     */
    declare public readonly networkBinding: pulumi.Output<string | undefined>;
    /**
     * Defaults to `seconds=0`.
     */
    declare public readonly rememberMeOffset: pulumi.Output<string | undefined>;
    /**
     * Defaults to `seconds=0`.
     */
    declare public readonly sessionDuration: pulumi.Output<string | undefined>;
    declare public readonly stageUserLoginId: pulumi.Output<string>;
    /**
     * Defaults to `false`.
     */
    declare public readonly terminateOtherSessions: pulumi.Output<boolean | undefined>;

    /**
     * Create a StageUserLogin resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: StageUserLoginArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: StageUserLoginArgs | StageUserLoginState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as StageUserLoginState | undefined;
            resourceInputs["geoipBinding"] = state?.geoipBinding;
            resourceInputs["name"] = state?.name;
            resourceInputs["networkBinding"] = state?.networkBinding;
            resourceInputs["rememberMeOffset"] = state?.rememberMeOffset;
            resourceInputs["sessionDuration"] = state?.sessionDuration;
            resourceInputs["stageUserLoginId"] = state?.stageUserLoginId;
            resourceInputs["terminateOtherSessions"] = state?.terminateOtherSessions;
        } else {
            const args = argsOrState as StageUserLoginArgs | undefined;
            resourceInputs["geoipBinding"] = args?.geoipBinding;
            resourceInputs["name"] = args?.name;
            resourceInputs["networkBinding"] = args?.networkBinding;
            resourceInputs["rememberMeOffset"] = args?.rememberMeOffset;
            resourceInputs["sessionDuration"] = args?.sessionDuration;
            resourceInputs["stageUserLoginId"] = args?.stageUserLoginId;
            resourceInputs["terminateOtherSessions"] = args?.terminateOtherSessions;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(StageUserLogin.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering StageUserLogin resources.
 */
export interface StageUserLoginState {
    /**
     * Allowed values: - `no_binding` - `bind_continent` - `bind_continent_country` - `bind_continent_country_city` Defaults to
     * `no_binding`.
     */
    geoipBinding?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    /**
     * Allowed values: - `no_binding` - `bind_asn` - `bind_asn_network` - `bind_asn_network_ip` Defaults to `no_binding`.
     */
    networkBinding?: pulumi.Input<string>;
    /**
     * Defaults to `seconds=0`.
     */
    rememberMeOffset?: pulumi.Input<string>;
    /**
     * Defaults to `seconds=0`.
     */
    sessionDuration?: pulumi.Input<string>;
    stageUserLoginId?: pulumi.Input<string>;
    /**
     * Defaults to `false`.
     */
    terminateOtherSessions?: pulumi.Input<boolean>;
}

/**
 * The set of arguments for constructing a StageUserLogin resource.
 */
export interface StageUserLoginArgs {
    /**
     * Allowed values: - `no_binding` - `bind_continent` - `bind_continent_country` - `bind_continent_country_city` Defaults to
     * `no_binding`.
     */
    geoipBinding?: pulumi.Input<string>;
    name?: pulumi.Input<string>;
    /**
     * Allowed values: - `no_binding` - `bind_asn` - `bind_asn_network` - `bind_asn_network_ip` Defaults to `no_binding`.
     */
    networkBinding?: pulumi.Input<string>;
    /**
     * Defaults to `seconds=0`.
     */
    rememberMeOffset?: pulumi.Input<string>;
    /**
     * Defaults to `seconds=0`.
     */
    sessionDuration?: pulumi.Input<string>;
    stageUserLoginId?: pulumi.Input<string>;
    /**
     * Defaults to `false`.
     */
    terminateOtherSessions?: pulumi.Input<boolean>;
}
