// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class StageEndpoints extends pulumi.CustomResource {
    /**
     * Get an existing StageEndpoints resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: StageEndpointsState, opts?: pulumi.CustomResourceOptions): StageEndpoints {
        return new StageEndpoints(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'authentik:index/stageEndpoints:StageEndpoints';

    /**
     * Returns true if the given object is an instance of StageEndpoints.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is StageEndpoints {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === StageEndpoints.__pulumiType;
    }

    declare public readonly connector: pulumi.Output<string>;
    /**
     * Allowed values:
     *   - <span pulumi-lang-nodejs="`optional`" pulumi-lang-dotnet="`Optional`" pulumi-lang-go="`optional`" pulumi-lang-python="`optional`" pulumi-lang-yaml="`optional`" pulumi-lang-java="`optional`" pulumi-lang-hcl="`optional`">`optional`</span>
     *   - <span pulumi-lang-nodejs="`required`" pulumi-lang-dotnet="`Required`" pulumi-lang-go="`required`" pulumi-lang-python="`required`" pulumi-lang-yaml="`required`" pulumi-lang-java="`required`" pulumi-lang-hcl="`required`">`required`</span>
     *      Defaults to <span pulumi-lang-nodejs="`optional`" pulumi-lang-dotnet="`Optional`" pulumi-lang-go="`optional`" pulumi-lang-python="`optional`" pulumi-lang-yaml="`optional`" pulumi-lang-java="`optional`" pulumi-lang-hcl="`optional`">`optional`</span>.
     */
    declare public readonly mode: pulumi.Output<string | undefined>;
    declare public readonly name: pulumi.Output<string>;
    declare public readonly stageEndpointsId: pulumi.Output<string>;

    /**
     * Create a StageEndpoints resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: StageEndpointsArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: StageEndpointsArgs | StageEndpointsState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as StageEndpointsState | undefined;
            resourceInputs["connector"] = state?.connector;
            resourceInputs["mode"] = state?.mode;
            resourceInputs["name"] = state?.name;
            resourceInputs["stageEndpointsId"] = state?.stageEndpointsId;
        } else {
            const args = argsOrState as StageEndpointsArgs | undefined;
            if (args?.connector === undefined && !opts.urn) {
                throw new Error("Missing required property 'connector'");
            }
            resourceInputs["connector"] = args?.connector;
            resourceInputs["mode"] = args?.mode;
            resourceInputs["name"] = args?.name;
            resourceInputs["stageEndpointsId"] = args?.stageEndpointsId;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(StageEndpoints.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering StageEndpoints resources.
 */
export interface StageEndpointsState {
    connector?: pulumi.Input<string | undefined>;
    /**
     * Allowed values:
     *   - <span pulumi-lang-nodejs="`optional`" pulumi-lang-dotnet="`Optional`" pulumi-lang-go="`optional`" pulumi-lang-python="`optional`" pulumi-lang-yaml="`optional`" pulumi-lang-java="`optional`" pulumi-lang-hcl="`optional`">`optional`</span>
     *   - <span pulumi-lang-nodejs="`required`" pulumi-lang-dotnet="`Required`" pulumi-lang-go="`required`" pulumi-lang-python="`required`" pulumi-lang-yaml="`required`" pulumi-lang-java="`required`" pulumi-lang-hcl="`required`">`required`</span>
     *      Defaults to <span pulumi-lang-nodejs="`optional`" pulumi-lang-dotnet="`Optional`" pulumi-lang-go="`optional`" pulumi-lang-python="`optional`" pulumi-lang-yaml="`optional`" pulumi-lang-java="`optional`" pulumi-lang-hcl="`optional`">`optional`</span>.
     */
    mode?: pulumi.Input<string | undefined>;
    name?: pulumi.Input<string | undefined>;
    stageEndpointsId?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a StageEndpoints resource.
 */
export interface StageEndpointsArgs {
    connector: pulumi.Input<string>;
    /**
     * Allowed values:
     *   - <span pulumi-lang-nodejs="`optional`" pulumi-lang-dotnet="`Optional`" pulumi-lang-go="`optional`" pulumi-lang-python="`optional`" pulumi-lang-yaml="`optional`" pulumi-lang-java="`optional`" pulumi-lang-hcl="`optional`">`optional`</span>
     *   - <span pulumi-lang-nodejs="`required`" pulumi-lang-dotnet="`Required`" pulumi-lang-go="`required`" pulumi-lang-python="`required`" pulumi-lang-yaml="`required`" pulumi-lang-java="`required`" pulumi-lang-hcl="`required`">`required`</span>
     *      Defaults to <span pulumi-lang-nodejs="`optional`" pulumi-lang-dotnet="`Optional`" pulumi-lang-go="`optional`" pulumi-lang-python="`optional`" pulumi-lang-yaml="`optional`" pulumi-lang-java="`optional`" pulumi-lang-hcl="`optional`">`optional`</span>.
     */
    mode?: pulumi.Input<string | undefined>;
    name?: pulumi.Input<string | undefined>;
    stageEndpointsId?: pulumi.Input<string | undefined>;
}
