// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class StageAuthenticatorValidate extends pulumi.CustomResource {
    /**
     * Get an existing StageAuthenticatorValidate resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: StageAuthenticatorValidateState, opts?: pulumi.CustomResourceOptions): StageAuthenticatorValidate {
        return new StageAuthenticatorValidate(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'authentik:index/stageAuthenticatorValidate:StageAuthenticatorValidate';

    /**
     * Returns true if the given object is an instance of StageAuthenticatorValidate.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is StageAuthenticatorValidate {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === StageAuthenticatorValidate.__pulumiType;
    }

    declare public readonly configurationStages: pulumi.Output<string[] | undefined>;
    declare public readonly deviceClasses: pulumi.Output<string[] | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`" pulumi-lang-hcl="`1`">`1`</span>.
     */
    declare public readonly emailOtpThrottlingFactor: pulumi.Output<number | undefined>;
    /**
     * Format: hours=1;minutes=2;seconds=3. Defaults to `seconds=0`.
     */
    declare public readonly lastAuthThreshold: pulumi.Output<string | undefined>;
    declare public readonly name: pulumi.Output<string>;
    /**
     * Allowed values:
     *   - <span pulumi-lang-nodejs="`skip`" pulumi-lang-dotnet="`Skip`" pulumi-lang-go="`skip`" pulumi-lang-python="`skip`" pulumi-lang-yaml="`skip`" pulumi-lang-java="`skip`" pulumi-lang-hcl="`skip`">`skip`</span>
     *   - <span pulumi-lang-nodejs="`deny`" pulumi-lang-dotnet="`Deny`" pulumi-lang-go="`deny`" pulumi-lang-python="`deny`" pulumi-lang-yaml="`deny`" pulumi-lang-java="`deny`" pulumi-lang-hcl="`deny`">`deny`</span>
     *   - <span pulumi-lang-nodejs="`configure`" pulumi-lang-dotnet="`Configure`" pulumi-lang-go="`configure`" pulumi-lang-python="`configure`" pulumi-lang-yaml="`configure`" pulumi-lang-java="`configure`" pulumi-lang-hcl="`configure`">`configure`</span>
     */
    declare public readonly notConfiguredAction: pulumi.Output<string>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`" pulumi-lang-hcl="`1`">`1`</span>.
     */
    declare public readonly smsOtpThrottlingFactor: pulumi.Output<number | undefined>;
    declare public readonly stageAuthenticatorValidateId: pulumi.Output<string>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`" pulumi-lang-hcl="`1`">`1`</span>.
     */
    declare public readonly staticOtpThrottlingFactor: pulumi.Output<number | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`" pulumi-lang-hcl="`1`">`1`</span>.
     */
    declare public readonly totpOtpThrottlingFactor: pulumi.Output<number | undefined>;
    declare public readonly webauthnAllowedDeviceTypes: pulumi.Output<string[] | undefined>;
    declare public readonly webauthnHints: pulumi.Output<string[] | undefined>;
    /**
     * Allowed values:
     *   - <span pulumi-lang-nodejs="`required`" pulumi-lang-dotnet="`Required`" pulumi-lang-go="`required`" pulumi-lang-python="`required`" pulumi-lang-yaml="`required`" pulumi-lang-java="`required`" pulumi-lang-hcl="`required`">`required`</span>
     *   - <span pulumi-lang-nodejs="`preferred`" pulumi-lang-dotnet="`Preferred`" pulumi-lang-go="`preferred`" pulumi-lang-python="`preferred`" pulumi-lang-yaml="`preferred`" pulumi-lang-java="`preferred`" pulumi-lang-hcl="`preferred`">`preferred`</span>
     *   - <span pulumi-lang-nodejs="`discouraged`" pulumi-lang-dotnet="`Discouraged`" pulumi-lang-go="`discouraged`" pulumi-lang-python="`discouraged`" pulumi-lang-yaml="`discouraged`" pulumi-lang-java="`discouraged`" pulumi-lang-hcl="`discouraged`">`discouraged`</span>
     *      Defaults to <span pulumi-lang-nodejs="`preferred`" pulumi-lang-dotnet="`Preferred`" pulumi-lang-go="`preferred`" pulumi-lang-python="`preferred`" pulumi-lang-yaml="`preferred`" pulumi-lang-java="`preferred`" pulumi-lang-hcl="`preferred`">`preferred`</span>.
     */
    declare public readonly webauthnUserVerification: pulumi.Output<string | undefined>;

    /**
     * Create a StageAuthenticatorValidate resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: StageAuthenticatorValidateArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: StageAuthenticatorValidateArgs | StageAuthenticatorValidateState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as StageAuthenticatorValidateState | undefined;
            resourceInputs["configurationStages"] = state?.configurationStages;
            resourceInputs["deviceClasses"] = state?.deviceClasses;
            resourceInputs["emailOtpThrottlingFactor"] = state?.emailOtpThrottlingFactor;
            resourceInputs["lastAuthThreshold"] = state?.lastAuthThreshold;
            resourceInputs["name"] = state?.name;
            resourceInputs["notConfiguredAction"] = state?.notConfiguredAction;
            resourceInputs["smsOtpThrottlingFactor"] = state?.smsOtpThrottlingFactor;
            resourceInputs["stageAuthenticatorValidateId"] = state?.stageAuthenticatorValidateId;
            resourceInputs["staticOtpThrottlingFactor"] = state?.staticOtpThrottlingFactor;
            resourceInputs["totpOtpThrottlingFactor"] = state?.totpOtpThrottlingFactor;
            resourceInputs["webauthnAllowedDeviceTypes"] = state?.webauthnAllowedDeviceTypes;
            resourceInputs["webauthnHints"] = state?.webauthnHints;
            resourceInputs["webauthnUserVerification"] = state?.webauthnUserVerification;
        } else {
            const args = argsOrState as StageAuthenticatorValidateArgs | undefined;
            if (args?.notConfiguredAction === undefined && !opts.urn) {
                throw new Error("Missing required property 'notConfiguredAction'");
            }
            resourceInputs["configurationStages"] = args?.configurationStages;
            resourceInputs["deviceClasses"] = args?.deviceClasses;
            resourceInputs["emailOtpThrottlingFactor"] = args?.emailOtpThrottlingFactor;
            resourceInputs["lastAuthThreshold"] = args?.lastAuthThreshold;
            resourceInputs["name"] = args?.name;
            resourceInputs["notConfiguredAction"] = args?.notConfiguredAction;
            resourceInputs["smsOtpThrottlingFactor"] = args?.smsOtpThrottlingFactor;
            resourceInputs["stageAuthenticatorValidateId"] = args?.stageAuthenticatorValidateId;
            resourceInputs["staticOtpThrottlingFactor"] = args?.staticOtpThrottlingFactor;
            resourceInputs["totpOtpThrottlingFactor"] = args?.totpOtpThrottlingFactor;
            resourceInputs["webauthnAllowedDeviceTypes"] = args?.webauthnAllowedDeviceTypes;
            resourceInputs["webauthnHints"] = args?.webauthnHints;
            resourceInputs["webauthnUserVerification"] = args?.webauthnUserVerification;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(StageAuthenticatorValidate.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering StageAuthenticatorValidate resources.
 */
export interface StageAuthenticatorValidateState {
    configurationStages?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    deviceClasses?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`" pulumi-lang-hcl="`1`">`1`</span>.
     */
    emailOtpThrottlingFactor?: pulumi.Input<number | undefined>;
    /**
     * Format: hours=1;minutes=2;seconds=3. Defaults to `seconds=0`.
     */
    lastAuthThreshold?: pulumi.Input<string | undefined>;
    name?: pulumi.Input<string | undefined>;
    /**
     * Allowed values:
     *   - <span pulumi-lang-nodejs="`skip`" pulumi-lang-dotnet="`Skip`" pulumi-lang-go="`skip`" pulumi-lang-python="`skip`" pulumi-lang-yaml="`skip`" pulumi-lang-java="`skip`" pulumi-lang-hcl="`skip`">`skip`</span>
     *   - <span pulumi-lang-nodejs="`deny`" pulumi-lang-dotnet="`Deny`" pulumi-lang-go="`deny`" pulumi-lang-python="`deny`" pulumi-lang-yaml="`deny`" pulumi-lang-java="`deny`" pulumi-lang-hcl="`deny`">`deny`</span>
     *   - <span pulumi-lang-nodejs="`configure`" pulumi-lang-dotnet="`Configure`" pulumi-lang-go="`configure`" pulumi-lang-python="`configure`" pulumi-lang-yaml="`configure`" pulumi-lang-java="`configure`" pulumi-lang-hcl="`configure`">`configure`</span>
     */
    notConfiguredAction?: pulumi.Input<string | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`" pulumi-lang-hcl="`1`">`1`</span>.
     */
    smsOtpThrottlingFactor?: pulumi.Input<number | undefined>;
    stageAuthenticatorValidateId?: pulumi.Input<string | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`" pulumi-lang-hcl="`1`">`1`</span>.
     */
    staticOtpThrottlingFactor?: pulumi.Input<number | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`" pulumi-lang-hcl="`1`">`1`</span>.
     */
    totpOtpThrottlingFactor?: pulumi.Input<number | undefined>;
    webauthnAllowedDeviceTypes?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    webauthnHints?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Allowed values:
     *   - <span pulumi-lang-nodejs="`required`" pulumi-lang-dotnet="`Required`" pulumi-lang-go="`required`" pulumi-lang-python="`required`" pulumi-lang-yaml="`required`" pulumi-lang-java="`required`" pulumi-lang-hcl="`required`">`required`</span>
     *   - <span pulumi-lang-nodejs="`preferred`" pulumi-lang-dotnet="`Preferred`" pulumi-lang-go="`preferred`" pulumi-lang-python="`preferred`" pulumi-lang-yaml="`preferred`" pulumi-lang-java="`preferred`" pulumi-lang-hcl="`preferred`">`preferred`</span>
     *   - <span pulumi-lang-nodejs="`discouraged`" pulumi-lang-dotnet="`Discouraged`" pulumi-lang-go="`discouraged`" pulumi-lang-python="`discouraged`" pulumi-lang-yaml="`discouraged`" pulumi-lang-java="`discouraged`" pulumi-lang-hcl="`discouraged`">`discouraged`</span>
     *      Defaults to <span pulumi-lang-nodejs="`preferred`" pulumi-lang-dotnet="`Preferred`" pulumi-lang-go="`preferred`" pulumi-lang-python="`preferred`" pulumi-lang-yaml="`preferred`" pulumi-lang-java="`preferred`" pulumi-lang-hcl="`preferred`">`preferred`</span>.
     */
    webauthnUserVerification?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a StageAuthenticatorValidate resource.
 */
export interface StageAuthenticatorValidateArgs {
    configurationStages?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    deviceClasses?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`" pulumi-lang-hcl="`1`">`1`</span>.
     */
    emailOtpThrottlingFactor?: pulumi.Input<number | undefined>;
    /**
     * Format: hours=1;minutes=2;seconds=3. Defaults to `seconds=0`.
     */
    lastAuthThreshold?: pulumi.Input<string | undefined>;
    name?: pulumi.Input<string | undefined>;
    /**
     * Allowed values:
     *   - <span pulumi-lang-nodejs="`skip`" pulumi-lang-dotnet="`Skip`" pulumi-lang-go="`skip`" pulumi-lang-python="`skip`" pulumi-lang-yaml="`skip`" pulumi-lang-java="`skip`" pulumi-lang-hcl="`skip`">`skip`</span>
     *   - <span pulumi-lang-nodejs="`deny`" pulumi-lang-dotnet="`Deny`" pulumi-lang-go="`deny`" pulumi-lang-python="`deny`" pulumi-lang-yaml="`deny`" pulumi-lang-java="`deny`" pulumi-lang-hcl="`deny`">`deny`</span>
     *   - <span pulumi-lang-nodejs="`configure`" pulumi-lang-dotnet="`Configure`" pulumi-lang-go="`configure`" pulumi-lang-python="`configure`" pulumi-lang-yaml="`configure`" pulumi-lang-java="`configure`" pulumi-lang-hcl="`configure`">`configure`</span>
     */
    notConfiguredAction: pulumi.Input<string>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`" pulumi-lang-hcl="`1`">`1`</span>.
     */
    smsOtpThrottlingFactor?: pulumi.Input<number | undefined>;
    stageAuthenticatorValidateId?: pulumi.Input<string | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`" pulumi-lang-hcl="`1`">`1`</span>.
     */
    staticOtpThrottlingFactor?: pulumi.Input<number | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`1`" pulumi-lang-dotnet="`1`" pulumi-lang-go="`1`" pulumi-lang-python="`1`" pulumi-lang-yaml="`1`" pulumi-lang-java="`1`" pulumi-lang-hcl="`1`">`1`</span>.
     */
    totpOtpThrottlingFactor?: pulumi.Input<number | undefined>;
    webauthnAllowedDeviceTypes?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    webauthnHints?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Allowed values:
     *   - <span pulumi-lang-nodejs="`required`" pulumi-lang-dotnet="`Required`" pulumi-lang-go="`required`" pulumi-lang-python="`required`" pulumi-lang-yaml="`required`" pulumi-lang-java="`required`" pulumi-lang-hcl="`required`">`required`</span>
     *   - <span pulumi-lang-nodejs="`preferred`" pulumi-lang-dotnet="`Preferred`" pulumi-lang-go="`preferred`" pulumi-lang-python="`preferred`" pulumi-lang-yaml="`preferred`" pulumi-lang-java="`preferred`" pulumi-lang-hcl="`preferred`">`preferred`</span>
     *   - <span pulumi-lang-nodejs="`discouraged`" pulumi-lang-dotnet="`Discouraged`" pulumi-lang-go="`discouraged`" pulumi-lang-python="`discouraged`" pulumi-lang-yaml="`discouraged`" pulumi-lang-java="`discouraged`" pulumi-lang-hcl="`discouraged`">`discouraged`</span>
     *      Defaults to <span pulumi-lang-nodejs="`preferred`" pulumi-lang-dotnet="`Preferred`" pulumi-lang-go="`preferred`" pulumi-lang-python="`preferred`" pulumi-lang-yaml="`preferred`" pulumi-lang-java="`preferred`" pulumi-lang-hcl="`preferred`">`preferred`</span>.
     */
    webauthnUserVerification?: pulumi.Input<string | undefined>;
}
