// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class StageAccountLockdown extends pulumi.CustomResource {
    /**
     * Get an existing StageAccountLockdown resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: StageAccountLockdownState, opts?: pulumi.CustomResourceOptions): StageAccountLockdown {
        return new StageAccountLockdown(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'authentik:index/stageAccountLockdown:StageAccountLockdown';

    /**
     * Returns true if the given object is an instance of StageAccountLockdown.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is StageAccountLockdown {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === StageAccountLockdown.__pulumiType;
    }

    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
     */
    declare public readonly deactivateUser: pulumi.Output<boolean | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
     */
    declare public readonly deleteSessions: pulumi.Output<boolean | undefined>;
    declare public readonly name: pulumi.Output<string>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
     */
    declare public readonly revokeTokens: pulumi.Output<boolean | undefined>;
    declare public readonly selfServiceCompletionFlow: pulumi.Output<string | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
     */
    declare public readonly setUnusablePassword: pulumi.Output<boolean | undefined>;
    declare public readonly stageAccountLockdownId: pulumi.Output<string>;

    /**
     * Create a StageAccountLockdown resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: StageAccountLockdownArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: StageAccountLockdownArgs | StageAccountLockdownState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as StageAccountLockdownState | undefined;
            resourceInputs["deactivateUser"] = state?.deactivateUser;
            resourceInputs["deleteSessions"] = state?.deleteSessions;
            resourceInputs["name"] = state?.name;
            resourceInputs["revokeTokens"] = state?.revokeTokens;
            resourceInputs["selfServiceCompletionFlow"] = state?.selfServiceCompletionFlow;
            resourceInputs["setUnusablePassword"] = state?.setUnusablePassword;
            resourceInputs["stageAccountLockdownId"] = state?.stageAccountLockdownId;
        } else {
            const args = argsOrState as StageAccountLockdownArgs | undefined;
            resourceInputs["deactivateUser"] = args?.deactivateUser;
            resourceInputs["deleteSessions"] = args?.deleteSessions;
            resourceInputs["name"] = args?.name;
            resourceInputs["revokeTokens"] = args?.revokeTokens;
            resourceInputs["selfServiceCompletionFlow"] = args?.selfServiceCompletionFlow;
            resourceInputs["setUnusablePassword"] = args?.setUnusablePassword;
            resourceInputs["stageAccountLockdownId"] = args?.stageAccountLockdownId;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(StageAccountLockdown.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering StageAccountLockdown resources.
 */
export interface StageAccountLockdownState {
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
     */
    deactivateUser?: pulumi.Input<boolean | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
     */
    deleteSessions?: pulumi.Input<boolean | undefined>;
    name?: pulumi.Input<string | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
     */
    revokeTokens?: pulumi.Input<boolean | undefined>;
    selfServiceCompletionFlow?: pulumi.Input<string | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
     */
    setUnusablePassword?: pulumi.Input<boolean | undefined>;
    stageAccountLockdownId?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a StageAccountLockdown resource.
 */
export interface StageAccountLockdownArgs {
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
     */
    deactivateUser?: pulumi.Input<boolean | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
     */
    deleteSessions?: pulumi.Input<boolean | undefined>;
    name?: pulumi.Input<string | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
     */
    revokeTokens?: pulumi.Input<boolean | undefined>;
    selfServiceCompletionFlow?: pulumi.Input<string | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`true`" pulumi-lang-dotnet="`True`" pulumi-lang-go="`true`" pulumi-lang-python="`true`" pulumi-lang-yaml="`true`" pulumi-lang-java="`true`" pulumi-lang-hcl="`true`">`true`</span>.
     */
    setUnusablePassword?: pulumi.Input<boolean | undefined>;
    stageAccountLockdownId?: pulumi.Input<string | undefined>;
}
