// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class SystemSettings extends pulumi.CustomResource {
    /**
     * Get an existing SystemSettings resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: SystemSettingsState, opts?: pulumi.CustomResourceOptions): SystemSettings {
        return new SystemSettings(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'authentik:index/systemSettings:SystemSettings';

    /**
     * Returns true if the given object is an instance of SystemSettings.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is SystemSettings {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === SystemSettings.__pulumiType;
    }

    /**
     * Defaults to `gravatar,initials`.
     */
    declare public readonly avatars: pulumi.Output<string | undefined>;
    /**
     * Format: hours=1;minutes=2;seconds=3. Defaults to `minutes=30`.
     */
    declare public readonly defaultTokenDuration: pulumi.Output<string | undefined>;
    /**
     * Defaults to `60`.
     */
    declare public readonly defaultTokenLength: pulumi.Output<number | undefined>;
    /**
     * Defaults to `false`.
     */
    declare public readonly defaultUserChangeEmail: pulumi.Output<boolean | undefined>;
    /**
     * Defaults to `true`.
     */
    declare public readonly defaultUserChangeName: pulumi.Output<boolean | undefined>;
    /**
     * Defaults to `false`.
     */
    declare public readonly defaultUserChangeUsername: pulumi.Output<boolean | undefined>;
    /**
     * Format: hours=1;minutes=2;seconds=3. Defaults to `days=365`.
     */
    declare public readonly eventRetention: pulumi.Output<string | undefined>;
    /**
     * JSON format expected. Use `jsonencode()` to pass objects. Defaults to `{"policies_buffered_access_view": false}`.
     */
    declare public readonly flags: pulumi.Output<string | undefined>;
    declare public readonly footerLinks: pulumi.Output<{[key: string]: string}[] | undefined>;
    /**
     * Defaults to `true`.
     */
    declare public readonly gdprCompliance: pulumi.Output<boolean | undefined>;
    /**
     * Defaults to `true`.
     */
    declare public readonly impersonation: pulumi.Output<boolean | undefined>;
    /**
     * Defaults to `-5`.
     */
    declare public readonly reputationLowerLimit: pulumi.Output<number | undefined>;
    /**
     * Defaults to `5`.
     */
    declare public readonly reputationUpperLimit: pulumi.Output<number | undefined>;
    declare public readonly systemSettingsId: pulumi.Output<string>;

    /**
     * Create a SystemSettings resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: SystemSettingsArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: SystemSettingsArgs | SystemSettingsState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as SystemSettingsState | undefined;
            resourceInputs["avatars"] = state?.avatars;
            resourceInputs["defaultTokenDuration"] = state?.defaultTokenDuration;
            resourceInputs["defaultTokenLength"] = state?.defaultTokenLength;
            resourceInputs["defaultUserChangeEmail"] = state?.defaultUserChangeEmail;
            resourceInputs["defaultUserChangeName"] = state?.defaultUserChangeName;
            resourceInputs["defaultUserChangeUsername"] = state?.defaultUserChangeUsername;
            resourceInputs["eventRetention"] = state?.eventRetention;
            resourceInputs["flags"] = state?.flags;
            resourceInputs["footerLinks"] = state?.footerLinks;
            resourceInputs["gdprCompliance"] = state?.gdprCompliance;
            resourceInputs["impersonation"] = state?.impersonation;
            resourceInputs["reputationLowerLimit"] = state?.reputationLowerLimit;
            resourceInputs["reputationUpperLimit"] = state?.reputationUpperLimit;
            resourceInputs["systemSettingsId"] = state?.systemSettingsId;
        } else {
            const args = argsOrState as SystemSettingsArgs | undefined;
            resourceInputs["avatars"] = args?.avatars;
            resourceInputs["defaultTokenDuration"] = args?.defaultTokenDuration;
            resourceInputs["defaultTokenLength"] = args?.defaultTokenLength;
            resourceInputs["defaultUserChangeEmail"] = args?.defaultUserChangeEmail;
            resourceInputs["defaultUserChangeName"] = args?.defaultUserChangeName;
            resourceInputs["defaultUserChangeUsername"] = args?.defaultUserChangeUsername;
            resourceInputs["eventRetention"] = args?.eventRetention;
            resourceInputs["flags"] = args?.flags;
            resourceInputs["footerLinks"] = args?.footerLinks;
            resourceInputs["gdprCompliance"] = args?.gdprCompliance;
            resourceInputs["impersonation"] = args?.impersonation;
            resourceInputs["reputationLowerLimit"] = args?.reputationLowerLimit;
            resourceInputs["reputationUpperLimit"] = args?.reputationUpperLimit;
            resourceInputs["systemSettingsId"] = args?.systemSettingsId;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(SystemSettings.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering SystemSettings resources.
 */
export interface SystemSettingsState {
    /**
     * Defaults to `gravatar,initials`.
     */
    avatars?: pulumi.Input<string>;
    /**
     * Format: hours=1;minutes=2;seconds=3. Defaults to `minutes=30`.
     */
    defaultTokenDuration?: pulumi.Input<string>;
    /**
     * Defaults to `60`.
     */
    defaultTokenLength?: pulumi.Input<number>;
    /**
     * Defaults to `false`.
     */
    defaultUserChangeEmail?: pulumi.Input<boolean>;
    /**
     * Defaults to `true`.
     */
    defaultUserChangeName?: pulumi.Input<boolean>;
    /**
     * Defaults to `false`.
     */
    defaultUserChangeUsername?: pulumi.Input<boolean>;
    /**
     * Format: hours=1;minutes=2;seconds=3. Defaults to `days=365`.
     */
    eventRetention?: pulumi.Input<string>;
    /**
     * JSON format expected. Use `jsonencode()` to pass objects. Defaults to `{"policies_buffered_access_view": false}`.
     */
    flags?: pulumi.Input<string>;
    footerLinks?: pulumi.Input<pulumi.Input<{[key: string]: pulumi.Input<string>}>[]>;
    /**
     * Defaults to `true`.
     */
    gdprCompliance?: pulumi.Input<boolean>;
    /**
     * Defaults to `true`.
     */
    impersonation?: pulumi.Input<boolean>;
    /**
     * Defaults to `-5`.
     */
    reputationLowerLimit?: pulumi.Input<number>;
    /**
     * Defaults to `5`.
     */
    reputationUpperLimit?: pulumi.Input<number>;
    systemSettingsId?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a SystemSettings resource.
 */
export interface SystemSettingsArgs {
    /**
     * Defaults to `gravatar,initials`.
     */
    avatars?: pulumi.Input<string>;
    /**
     * Format: hours=1;minutes=2;seconds=3. Defaults to `minutes=30`.
     */
    defaultTokenDuration?: pulumi.Input<string>;
    /**
     * Defaults to `60`.
     */
    defaultTokenLength?: pulumi.Input<number>;
    /**
     * Defaults to `false`.
     */
    defaultUserChangeEmail?: pulumi.Input<boolean>;
    /**
     * Defaults to `true`.
     */
    defaultUserChangeName?: pulumi.Input<boolean>;
    /**
     * Defaults to `false`.
     */
    defaultUserChangeUsername?: pulumi.Input<boolean>;
    /**
     * Format: hours=1;minutes=2;seconds=3. Defaults to `days=365`.
     */
    eventRetention?: pulumi.Input<string>;
    /**
     * JSON format expected. Use `jsonencode()` to pass objects. Defaults to `{"policies_buffered_access_view": false}`.
     */
    flags?: pulumi.Input<string>;
    footerLinks?: pulumi.Input<pulumi.Input<{[key: string]: pulumi.Input<string>}>[]>;
    /**
     * Defaults to `true`.
     */
    gdprCompliance?: pulumi.Input<boolean>;
    /**
     * Defaults to `true`.
     */
    impersonation?: pulumi.Input<boolean>;
    /**
     * Defaults to `-5`.
     */
    reputationLowerLimit?: pulumi.Input<number>;
    /**
     * Defaults to `5`.
     */
    reputationUpperLimit?: pulumi.Input<number>;
    systemSettingsId?: pulumi.Input<string>;
}
