// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class TaskSchedule extends pulumi.CustomResource {
    /**
     * Get an existing TaskSchedule resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: TaskScheduleState, opts?: pulumi.CustomResourceOptions): TaskSchedule {
        return new TaskSchedule(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'authentik:index/taskSchedule:TaskSchedule';

    /**
     * Returns true if the given object is an instance of TaskSchedule.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is TaskSchedule {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === TaskSchedule.__pulumiType;
    }

    declare public readonly actorName: pulumi.Output<string | undefined>;
    /**
     * Allowed values:
     *   - `authentik_tenants.domain`
     *   - `authentik_core.group`
     *   - `authentik_core.user`
     *   - `authentik_core.application`
     *   - `authentik_core.applicationentitlement`
     *   - `authentik_core.token`
     *   - `authentik_crypto.certificatekeypair`
     *   - `authentik_endpoints.deviceuserbinding`
     *   - `authentik_endpoints.deviceaccessgroup`
     *   - `authentik_endpoints.endpointstage`
     *   - `authentik_endpoints_connectors_agent.agentconnector`
     *   - `authentik_endpoints_connectors_agent.agentdeviceuserbinding`
     *   - `authentik_endpoints_connectors_agent.enrollmenttoken`
     *   - `authentik_enterprise.license`
     *   - `authentik_events.event`
     *   - `authentik_events.notificationtransport`
     *   - `authentik_events.notification`
     *   - `authentik_events.notificationrule`
     *   - `authentik_events.notificationwebhookmapping`
     *   - `authentik_flows.flow`
     *   - `authentik_flows.flowstagebinding`
     *   - `authentik_outposts.dockerserviceconnection`
     *   - `authentik_outposts.kubernetesserviceconnection`
     *   - `authentik_outposts.outpost`
     *   - `authentik_policies_dummy.dummypolicy`
     *   - `authentik_policies_event_matcher.eventmatcherpolicy`
     *   - `authentik_policies_expiry.passwordexpirypolicy`
     *   - `authentik_policies_expression.expressionpolicy`
     *   - `authentik_policies_geoip.geoippolicy`
     *   - `authentik_policies_password.passwordpolicy`
     *   - `authentik_policies_reputation.reputationpolicy`
     *   - `authentik_policies.policybinding`
     *   - `authentik_providers_ldap.ldapprovider`
     *   - `authentik_providers_oauth2.scopemapping`
     *   - `authentik_providers_oauth2.oauth2provider`
     *   - `authentik_providers_proxy.proxyprovider`
     *   - `authentik_providers_rac.racprovider`
     *   - `authentik_providers_rac.endpoint`
     *   - `authentik_providers_rac.racpropertymapping`
     *   - `authentik_providers_radius.radiusprovider`
     *   - `authentik_providers_radius.radiusproviderpropertymapping`
     *   - `authentik_providers_saml.samlprovider`
     *   - `authentik_providers_saml.samlpropertymapping`
     *   - `authentik_providers_scim.scimprovider`
     *   - `authentik_providers_scim.scimmapping`
     *   - `authentik_rbac.role`
     *   - `authentik_rbac.initialpermissions`
     *   - `authentik_sources_kerberos.kerberossource`
     *   - `authentik_sources_kerberos.kerberossourcepropertymapping`
     *   - `authentik_sources_kerberos.userkerberossourceconnection`
     *   - `authentik_sources_kerberos.groupkerberossourceconnection`
     *   - `authentik_sources_ldap.ldapsource`
     *   - `authentik_sources_ldap.ldapsourcepropertymapping`
     *   - `authentik_sources_ldap.userldapsourceconnection`
     *   - `authentik_sources_ldap.groupldapsourceconnection`
     *   - `authentik_sources_oauth.oauthsource`
     *   - `authentik_sources_oauth.oauthsourcepropertymapping`
     *   - `authentik_sources_oauth.useroauthsourceconnection`
     *   - `authentik_sources_oauth.groupoauthsourceconnection`
     *   - `authentik_sources_plex.plexsource`
     *   - `authentik_sources_plex.plexsourcepropertymapping`
     *   - `authentik_sources_plex.userplexsourceconnection`
     *   - `authentik_sources_plex.groupplexsourceconnection`
     *   - `authentik_sources_saml.samlsource`
     *   - `authentik_sources_saml.samlsourcepropertymapping`
     *   - `authentik_sources_saml.usersamlsourceconnection`
     *   - `authentik_sources_saml.groupsamlsourceconnection`
     *   - `authentik_sources_scim.scimsource`
     *   - `authentik_sources_scim.scimsourcepropertymapping`
     *   - `authentik_sources_telegram.telegramsource`
     *   - `authentik_sources_telegram.telegramsourcepropertymapping`
     *   - `authentik_sources_telegram.usertelegramsourceconnection`
     *   - `authentik_sources_telegram.grouptelegramsourceconnection`
     *   - `authentik_stages_authenticator_duo.authenticatorduostage`
     *   - `authentik_stages_authenticator_duo.duodevice`
     *   - `authentik_stages_authenticator_email.authenticatoremailstage`
     *   - `authentik_stages_authenticator_email.emaildevice`
     *   - `authentik_stages_authenticator_sms.authenticatorsmsstage`
     *   - `authentik_stages_authenticator_sms.smsdevice`
     *   - `authentik_stages_authenticator_static.authenticatorstaticstage`
     *   - `authentik_stages_authenticator_static.staticdevice`
     *   - `authentik_stages_authenticator_totp.authenticatortotpstage`
     *   - `authentik_stages_authenticator_totp.totpdevice`
     *   - `authentik_stages_authenticator_validate.authenticatorvalidatestage`
     *   - `authentik_stages_authenticator_webauthn.authenticatorwebauthnstage`
     *   - `authentik_stages_authenticator_webauthn.webauthndevice`
     *   - `authentik_stages_captcha.captchastage`
     *   - `authentik_stages_consent.consentstage`
     *   - `authentik_stages_deny.denystage`
     *   - `authentik_stages_dummy.dummystage`
     *   - `authentik_stages_email.emailstage`
     *   - `authentik_stages_identification.identificationstage`
     *   - `authentik_stages_invitation.invitationstage`
     *   - `authentik_stages_invitation.invitation`
     *   - `authentik_stages_password.passwordstage`
     *   - `authentik_stages_prompt.prompt`
     *   - `authentik_stages_prompt.promptstage`
     *   - `authentik_stages_redirect.redirectstage`
     *   - `authentik_stages_user_delete.userdeletestage`
     *   - `authentik_stages_user_login.userloginstage`
     *   - `authentik_stages_user_logout.userlogoutstage`
     *   - `authentik_stages_user_write.userwritestage`
     *   - `authentik_tasks_schedules.schedule`
     *   - `authentik_brands.brand`
     *   - `authentik_blueprints.blueprintinstance`
     *   - `authentik_endpoints_connectors_fleet.fleetconnector`
     *   - `authentik_endpoints_connectors_google_chrome.googlechromeconnector`
     *   - `authentik_lifecycle.lifecyclerule`
     *   - `authentik_lifecycle.lifecycleiteration`
     *   - `authentik_lifecycle.review`
     *   - `authentik_policies_unique_password.uniquepasswordpolicy`
     *   - `authentik_providers_google_workspace.googleworkspaceprovider`
     *   - `authentik_providers_google_workspace.googleworkspaceprovidermapping`
     *   - `authentik_providers_microsoft_entra.microsoftentraprovider`
     *   - `authentik_providers_microsoft_entra.microsoftentraprovidermapping`
     *   - `authentik_providers_ssf.ssfprovider`
     *   - `authentik_providers_ws_federation.wsfederationprovider`
     *   - `authentik_reports.dataexport`
     *   - `authentik_stages_account_lockdown.accountlockdownstage`
     *   - `authentik_stages_authenticator_endpoint_gdtc.authenticatorendpointgdtcstage`
     *   - `authentik_stages_mtls.mutualtlsstage`
     *   - `authentik_stages_source.sourcestage`
     */
    declare public readonly appModel: pulumi.Output<string>;
    /**
     * Crontab expression at which this task will run.
     */
    declare public readonly crontab: pulumi.Output<string>;
    declare public readonly modelId: pulumi.Output<string>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
     */
    declare public readonly paused: pulumi.Output<boolean | undefined>;
    declare public readonly taskScheduleId: pulumi.Output<string>;

    /**
     * Create a TaskSchedule resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: TaskScheduleArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: TaskScheduleArgs | TaskScheduleState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as TaskScheduleState | undefined;
            resourceInputs["actorName"] = state?.actorName;
            resourceInputs["appModel"] = state?.appModel;
            resourceInputs["crontab"] = state?.crontab;
            resourceInputs["modelId"] = state?.modelId;
            resourceInputs["paused"] = state?.paused;
            resourceInputs["taskScheduleId"] = state?.taskScheduleId;
        } else {
            const args = argsOrState as TaskScheduleArgs | undefined;
            if (args?.appModel === undefined && !opts.urn) {
                throw new Error("Missing required property 'appModel'");
            }
            if (args?.crontab === undefined && !opts.urn) {
                throw new Error("Missing required property 'crontab'");
            }
            if (args?.modelId === undefined && !opts.urn) {
                throw new Error("Missing required property 'modelId'");
            }
            resourceInputs["actorName"] = args?.actorName;
            resourceInputs["appModel"] = args?.appModel;
            resourceInputs["crontab"] = args?.crontab;
            resourceInputs["modelId"] = args?.modelId;
            resourceInputs["paused"] = args?.paused;
            resourceInputs["taskScheduleId"] = args?.taskScheduleId;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(TaskSchedule.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering TaskSchedule resources.
 */
export interface TaskScheduleState {
    actorName?: pulumi.Input<string | undefined>;
    /**
     * Allowed values:
     *   - `authentik_tenants.domain`
     *   - `authentik_core.group`
     *   - `authentik_core.user`
     *   - `authentik_core.application`
     *   - `authentik_core.applicationentitlement`
     *   - `authentik_core.token`
     *   - `authentik_crypto.certificatekeypair`
     *   - `authentik_endpoints.deviceuserbinding`
     *   - `authentik_endpoints.deviceaccessgroup`
     *   - `authentik_endpoints.endpointstage`
     *   - `authentik_endpoints_connectors_agent.agentconnector`
     *   - `authentik_endpoints_connectors_agent.agentdeviceuserbinding`
     *   - `authentik_endpoints_connectors_agent.enrollmenttoken`
     *   - `authentik_enterprise.license`
     *   - `authentik_events.event`
     *   - `authentik_events.notificationtransport`
     *   - `authentik_events.notification`
     *   - `authentik_events.notificationrule`
     *   - `authentik_events.notificationwebhookmapping`
     *   - `authentik_flows.flow`
     *   - `authentik_flows.flowstagebinding`
     *   - `authentik_outposts.dockerserviceconnection`
     *   - `authentik_outposts.kubernetesserviceconnection`
     *   - `authentik_outposts.outpost`
     *   - `authentik_policies_dummy.dummypolicy`
     *   - `authentik_policies_event_matcher.eventmatcherpolicy`
     *   - `authentik_policies_expiry.passwordexpirypolicy`
     *   - `authentik_policies_expression.expressionpolicy`
     *   - `authentik_policies_geoip.geoippolicy`
     *   - `authentik_policies_password.passwordpolicy`
     *   - `authentik_policies_reputation.reputationpolicy`
     *   - `authentik_policies.policybinding`
     *   - `authentik_providers_ldap.ldapprovider`
     *   - `authentik_providers_oauth2.scopemapping`
     *   - `authentik_providers_oauth2.oauth2provider`
     *   - `authentik_providers_proxy.proxyprovider`
     *   - `authentik_providers_rac.racprovider`
     *   - `authentik_providers_rac.endpoint`
     *   - `authentik_providers_rac.racpropertymapping`
     *   - `authentik_providers_radius.radiusprovider`
     *   - `authentik_providers_radius.radiusproviderpropertymapping`
     *   - `authentik_providers_saml.samlprovider`
     *   - `authentik_providers_saml.samlpropertymapping`
     *   - `authentik_providers_scim.scimprovider`
     *   - `authentik_providers_scim.scimmapping`
     *   - `authentik_rbac.role`
     *   - `authentik_rbac.initialpermissions`
     *   - `authentik_sources_kerberos.kerberossource`
     *   - `authentik_sources_kerberos.kerberossourcepropertymapping`
     *   - `authentik_sources_kerberos.userkerberossourceconnection`
     *   - `authentik_sources_kerberos.groupkerberossourceconnection`
     *   - `authentik_sources_ldap.ldapsource`
     *   - `authentik_sources_ldap.ldapsourcepropertymapping`
     *   - `authentik_sources_ldap.userldapsourceconnection`
     *   - `authentik_sources_ldap.groupldapsourceconnection`
     *   - `authentik_sources_oauth.oauthsource`
     *   - `authentik_sources_oauth.oauthsourcepropertymapping`
     *   - `authentik_sources_oauth.useroauthsourceconnection`
     *   - `authentik_sources_oauth.groupoauthsourceconnection`
     *   - `authentik_sources_plex.plexsource`
     *   - `authentik_sources_plex.plexsourcepropertymapping`
     *   - `authentik_sources_plex.userplexsourceconnection`
     *   - `authentik_sources_plex.groupplexsourceconnection`
     *   - `authentik_sources_saml.samlsource`
     *   - `authentik_sources_saml.samlsourcepropertymapping`
     *   - `authentik_sources_saml.usersamlsourceconnection`
     *   - `authentik_sources_saml.groupsamlsourceconnection`
     *   - `authentik_sources_scim.scimsource`
     *   - `authentik_sources_scim.scimsourcepropertymapping`
     *   - `authentik_sources_telegram.telegramsource`
     *   - `authentik_sources_telegram.telegramsourcepropertymapping`
     *   - `authentik_sources_telegram.usertelegramsourceconnection`
     *   - `authentik_sources_telegram.grouptelegramsourceconnection`
     *   - `authentik_stages_authenticator_duo.authenticatorduostage`
     *   - `authentik_stages_authenticator_duo.duodevice`
     *   - `authentik_stages_authenticator_email.authenticatoremailstage`
     *   - `authentik_stages_authenticator_email.emaildevice`
     *   - `authentik_stages_authenticator_sms.authenticatorsmsstage`
     *   - `authentik_stages_authenticator_sms.smsdevice`
     *   - `authentik_stages_authenticator_static.authenticatorstaticstage`
     *   - `authentik_stages_authenticator_static.staticdevice`
     *   - `authentik_stages_authenticator_totp.authenticatortotpstage`
     *   - `authentik_stages_authenticator_totp.totpdevice`
     *   - `authentik_stages_authenticator_validate.authenticatorvalidatestage`
     *   - `authentik_stages_authenticator_webauthn.authenticatorwebauthnstage`
     *   - `authentik_stages_authenticator_webauthn.webauthndevice`
     *   - `authentik_stages_captcha.captchastage`
     *   - `authentik_stages_consent.consentstage`
     *   - `authentik_stages_deny.denystage`
     *   - `authentik_stages_dummy.dummystage`
     *   - `authentik_stages_email.emailstage`
     *   - `authentik_stages_identification.identificationstage`
     *   - `authentik_stages_invitation.invitationstage`
     *   - `authentik_stages_invitation.invitation`
     *   - `authentik_stages_password.passwordstage`
     *   - `authentik_stages_prompt.prompt`
     *   - `authentik_stages_prompt.promptstage`
     *   - `authentik_stages_redirect.redirectstage`
     *   - `authentik_stages_user_delete.userdeletestage`
     *   - `authentik_stages_user_login.userloginstage`
     *   - `authentik_stages_user_logout.userlogoutstage`
     *   - `authentik_stages_user_write.userwritestage`
     *   - `authentik_tasks_schedules.schedule`
     *   - `authentik_brands.brand`
     *   - `authentik_blueprints.blueprintinstance`
     *   - `authentik_endpoints_connectors_fleet.fleetconnector`
     *   - `authentik_endpoints_connectors_google_chrome.googlechromeconnector`
     *   - `authentik_lifecycle.lifecyclerule`
     *   - `authentik_lifecycle.lifecycleiteration`
     *   - `authentik_lifecycle.review`
     *   - `authentik_policies_unique_password.uniquepasswordpolicy`
     *   - `authentik_providers_google_workspace.googleworkspaceprovider`
     *   - `authentik_providers_google_workspace.googleworkspaceprovidermapping`
     *   - `authentik_providers_microsoft_entra.microsoftentraprovider`
     *   - `authentik_providers_microsoft_entra.microsoftentraprovidermapping`
     *   - `authentik_providers_ssf.ssfprovider`
     *   - `authentik_providers_ws_federation.wsfederationprovider`
     *   - `authentik_reports.dataexport`
     *   - `authentik_stages_account_lockdown.accountlockdownstage`
     *   - `authentik_stages_authenticator_endpoint_gdtc.authenticatorendpointgdtcstage`
     *   - `authentik_stages_mtls.mutualtlsstage`
     *   - `authentik_stages_source.sourcestage`
     */
    appModel?: pulumi.Input<string | undefined>;
    /**
     * Crontab expression at which this task will run.
     */
    crontab?: pulumi.Input<string | undefined>;
    modelId?: pulumi.Input<string | undefined>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
     */
    paused?: pulumi.Input<boolean | undefined>;
    taskScheduleId?: pulumi.Input<string | undefined>;
}

/**
 * The set of arguments for constructing a TaskSchedule resource.
 */
export interface TaskScheduleArgs {
    actorName?: pulumi.Input<string | undefined>;
    /**
     * Allowed values:
     *   - `authentik_tenants.domain`
     *   - `authentik_core.group`
     *   - `authentik_core.user`
     *   - `authentik_core.application`
     *   - `authentik_core.applicationentitlement`
     *   - `authentik_core.token`
     *   - `authentik_crypto.certificatekeypair`
     *   - `authentik_endpoints.deviceuserbinding`
     *   - `authentik_endpoints.deviceaccessgroup`
     *   - `authentik_endpoints.endpointstage`
     *   - `authentik_endpoints_connectors_agent.agentconnector`
     *   - `authentik_endpoints_connectors_agent.agentdeviceuserbinding`
     *   - `authentik_endpoints_connectors_agent.enrollmenttoken`
     *   - `authentik_enterprise.license`
     *   - `authentik_events.event`
     *   - `authentik_events.notificationtransport`
     *   - `authentik_events.notification`
     *   - `authentik_events.notificationrule`
     *   - `authentik_events.notificationwebhookmapping`
     *   - `authentik_flows.flow`
     *   - `authentik_flows.flowstagebinding`
     *   - `authentik_outposts.dockerserviceconnection`
     *   - `authentik_outposts.kubernetesserviceconnection`
     *   - `authentik_outposts.outpost`
     *   - `authentik_policies_dummy.dummypolicy`
     *   - `authentik_policies_event_matcher.eventmatcherpolicy`
     *   - `authentik_policies_expiry.passwordexpirypolicy`
     *   - `authentik_policies_expression.expressionpolicy`
     *   - `authentik_policies_geoip.geoippolicy`
     *   - `authentik_policies_password.passwordpolicy`
     *   - `authentik_policies_reputation.reputationpolicy`
     *   - `authentik_policies.policybinding`
     *   - `authentik_providers_ldap.ldapprovider`
     *   - `authentik_providers_oauth2.scopemapping`
     *   - `authentik_providers_oauth2.oauth2provider`
     *   - `authentik_providers_proxy.proxyprovider`
     *   - `authentik_providers_rac.racprovider`
     *   - `authentik_providers_rac.endpoint`
     *   - `authentik_providers_rac.racpropertymapping`
     *   - `authentik_providers_radius.radiusprovider`
     *   - `authentik_providers_radius.radiusproviderpropertymapping`
     *   - `authentik_providers_saml.samlprovider`
     *   - `authentik_providers_saml.samlpropertymapping`
     *   - `authentik_providers_scim.scimprovider`
     *   - `authentik_providers_scim.scimmapping`
     *   - `authentik_rbac.role`
     *   - `authentik_rbac.initialpermissions`
     *   - `authentik_sources_kerberos.kerberossource`
     *   - `authentik_sources_kerberos.kerberossourcepropertymapping`
     *   - `authentik_sources_kerberos.userkerberossourceconnection`
     *   - `authentik_sources_kerberos.groupkerberossourceconnection`
     *   - `authentik_sources_ldap.ldapsource`
     *   - `authentik_sources_ldap.ldapsourcepropertymapping`
     *   - `authentik_sources_ldap.userldapsourceconnection`
     *   - `authentik_sources_ldap.groupldapsourceconnection`
     *   - `authentik_sources_oauth.oauthsource`
     *   - `authentik_sources_oauth.oauthsourcepropertymapping`
     *   - `authentik_sources_oauth.useroauthsourceconnection`
     *   - `authentik_sources_oauth.groupoauthsourceconnection`
     *   - `authentik_sources_plex.plexsource`
     *   - `authentik_sources_plex.plexsourcepropertymapping`
     *   - `authentik_sources_plex.userplexsourceconnection`
     *   - `authentik_sources_plex.groupplexsourceconnection`
     *   - `authentik_sources_saml.samlsource`
     *   - `authentik_sources_saml.samlsourcepropertymapping`
     *   - `authentik_sources_saml.usersamlsourceconnection`
     *   - `authentik_sources_saml.groupsamlsourceconnection`
     *   - `authentik_sources_scim.scimsource`
     *   - `authentik_sources_scim.scimsourcepropertymapping`
     *   - `authentik_sources_telegram.telegramsource`
     *   - `authentik_sources_telegram.telegramsourcepropertymapping`
     *   - `authentik_sources_telegram.usertelegramsourceconnection`
     *   - `authentik_sources_telegram.grouptelegramsourceconnection`
     *   - `authentik_stages_authenticator_duo.authenticatorduostage`
     *   - `authentik_stages_authenticator_duo.duodevice`
     *   - `authentik_stages_authenticator_email.authenticatoremailstage`
     *   - `authentik_stages_authenticator_email.emaildevice`
     *   - `authentik_stages_authenticator_sms.authenticatorsmsstage`
     *   - `authentik_stages_authenticator_sms.smsdevice`
     *   - `authentik_stages_authenticator_static.authenticatorstaticstage`
     *   - `authentik_stages_authenticator_static.staticdevice`
     *   - `authentik_stages_authenticator_totp.authenticatortotpstage`
     *   - `authentik_stages_authenticator_totp.totpdevice`
     *   - `authentik_stages_authenticator_validate.authenticatorvalidatestage`
     *   - `authentik_stages_authenticator_webauthn.authenticatorwebauthnstage`
     *   - `authentik_stages_authenticator_webauthn.webauthndevice`
     *   - `authentik_stages_captcha.captchastage`
     *   - `authentik_stages_consent.consentstage`
     *   - `authentik_stages_deny.denystage`
     *   - `authentik_stages_dummy.dummystage`
     *   - `authentik_stages_email.emailstage`
     *   - `authentik_stages_identification.identificationstage`
     *   - `authentik_stages_invitation.invitationstage`
     *   - `authentik_stages_invitation.invitation`
     *   - `authentik_stages_password.passwordstage`
     *   - `authentik_stages_prompt.prompt`
     *   - `authentik_stages_prompt.promptstage`
     *   - `authentik_stages_redirect.redirectstage`
     *   - `authentik_stages_user_delete.userdeletestage`
     *   - `authentik_stages_user_login.userloginstage`
     *   - `authentik_stages_user_logout.userlogoutstage`
     *   - `authentik_stages_user_write.userwritestage`
     *   - `authentik_tasks_schedules.schedule`
     *   - `authentik_brands.brand`
     *   - `authentik_blueprints.blueprintinstance`
     *   - `authentik_endpoints_connectors_fleet.fleetconnector`
     *   - `authentik_endpoints_connectors_google_chrome.googlechromeconnector`
     *   - `authentik_lifecycle.lifecyclerule`
     *   - `authentik_lifecycle.lifecycleiteration`
     *   - `authentik_lifecycle.review`
     *   - `authentik_policies_unique_password.uniquepasswordpolicy`
     *   - `authentik_providers_google_workspace.googleworkspaceprovider`
     *   - `authentik_providers_google_workspace.googleworkspaceprovidermapping`
     *   - `authentik_providers_microsoft_entra.microsoftentraprovider`
     *   - `authentik_providers_microsoft_entra.microsoftentraprovidermapping`
     *   - `authentik_providers_ssf.ssfprovider`
     *   - `authentik_providers_ws_federation.wsfederationprovider`
     *   - `authentik_reports.dataexport`
     *   - `authentik_stages_account_lockdown.accountlockdownstage`
     *   - `authentik_stages_authenticator_endpoint_gdtc.authenticatorendpointgdtcstage`
     *   - `authentik_stages_mtls.mutualtlsstage`
     *   - `authentik_stages_source.sourcestage`
     */
    appModel: pulumi.Input<string>;
    /**
     * Crontab expression at which this task will run.
     */
    crontab: pulumi.Input<string>;
    modelId: pulumi.Input<string>;
    /**
     * Defaults to <span pulumi-lang-nodejs="`false`" pulumi-lang-dotnet="`False`" pulumi-lang-go="`false`" pulumi-lang-python="`false`" pulumi-lang-yaml="`false`" pulumi-lang-java="`false`" pulumi-lang-hcl="`false`">`false`</span>.
     */
    paused?: pulumi.Input<boolean | undefined>;
    taskScheduleId?: pulumi.Input<string | undefined>;
}
